export const profiles = {
    // Iota
    Julian_Rachman: {
        linkedIn: "https://www.linkedin.com/in/julian-rachman/",
        homeTown: "Torrance, CA",
        year: "4th",
        class: "Iota",
        major: "Computer Science, Business Information Management",
        minor: "",
        emphasis: "",
        pronouns: "He/Him/His",
        practice: "Technology",
        experience: {"Founder & CEO": "Ripplink", "Summer Investor": "Two Sigma Ventures", "Professional Services Technical Consultant": "Amazon Web Services"},
        campusInvolvements: "",
        interests: ["Cryptocurrency", "Blockchain", "Ice Hockey"],
        whyLPN: "As a computer science major trying to find a place to break into the business ecosystem, I found that LPN is the best place for carrying out my ambitions while also being surrounded by an overly supportive family with generations before it. They really take their time to personally provide you with the best resources and guidance to set you on the right path towards achieving your end goal. To me, family is all about empowering those to carry out their ambitions, caring for each other unconditionally, and leaving a legacy behind for the next generation to fulfill their calling. I believe that the Lambda Phi Nu family embodies the description perfectly.",
        img: require("../../../../assets/actives/brothers/Julian_Rachman.jpg")
    },
    Karen_Ching: {
        linkedIn: "https://www.linkedin.com/in/kching/",
        homeTown: "San Francisco, CA",
        year: "4th",
        class: "Iota",
        major: "Education Sciences",
        minor: "",
        emphasis: "",
        practice: "Education",
        pronouns: "She/Her/Hers",
        experience: { "Mentor": "UCI School of Education", "Teacher Aide": "UCI child care services", "Research Assistant": "UCI Graduate Divison", "Peer Assistant": "UCI School of Education", "Marketing Intern": "HomeTown Financial Services" },
        campusInvolvements: { "Member Relations Director": "Marketing Association", "Corporate Relations Director": "Lambda Phi Nu", "CALPIRG": "" },
        interests: ["Baking", "Exploring new things", "Volleyball", "Traveling", "Hiking", "Drawing"],
        whyLPN: "Through my time in LPN, I was able to discover my true passions and interests. LPN has also given me some of the most memorable experiences that I never could've imagined. I have been so fortunate enough to build meaningful relationships with some of the brothers of LPN. Though it may feel like a rollercoaster, I appreciate all the memories and experiences that I've gained to help me grow, and I wouldn't want it any other way. LPN has helped me develop professionally, but I'm fortunate to have gained so much more.",
        img: require("../../../../assets/actives/brothers/Karen_Ching.jpg")
    },
    Vivi_Liu: {
        linkedIn: "https://www.linkedin.com/in/vivi-liu/",
        homeTown: "Taipei, Taiwan",
        year: "4th",
        class: "Iota",
        major: "Business Administration",
        minor: "Digital Arts",
        emphasis: "Marketing",
        practice: "Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Project Manager": "CrossBond Brand Consultant", "UCI School of Biological Sciences": "Assistant to Marketing Manager", "Digital Marketing Executive": "BigByte Education"},
        campusInvolvements: {"Mentorship Director": "Undergraduate Business Association", "VP of Internal Affairs": "Marketing Association", "Media and Communications Intern": "Associated Students of UCI"},
        interests: ["Bouldering", "Cooking", "Investing"],
        whyLPN: "My family in the United States :)",
        img: require("../../../../assets/actives/brothers/Vivi_Liu.jpg")
    },
    // Kappa
    Sandy_Nguyen: {
        linkedIn: "https://linkedin.com/in/-sandy-nguyen",
        homeTown: "West Covina, CA",
        year: "4th",
        class: "Kappa",
        major: "Business Administration",
        minor: "Informatics",
        emphasis: "Information Systems",
        practice: "Product Design (UX/UI)",
        pronouns: "She/Her/Hers",
        experience: {"Product Design Intern ": "MongoDB", "Product Design Intern": "McAfee", "UX Designer Intern": "Goinvo"},
        campusInvolvements: {"President": "Marketing Association", "Co-founder & VP of Finance": "Human Resources Management Association", "Student Intern": "Undergraduate Business Association"},
        interests: ["Gundams", "Painting", "Napping"],
        whyLPN: "Because why not?",
        img: require("../../../../assets/actives/brothers/Sandy_Nguyen.jpg")
    },
    Stephen_Minn: {
        linkedIn: "https://www.linkedin.com/in/stephenminn/",
        homeTown: "Stockton, CA",
        year: "4th",
        class: "Kappa",
        major: "Business Administration",
        minor: "",
        emphasis: "Organization & Management, Finance",
        practice: "Consulting",
        pronouns: "He/Him/His",
        experience: {"Supply Intern":"Kyte","Strategy & Operations Intern": "Ripplink", "Strategy Analyst": "Embolden", "Finance Intern": "KLK Capital Management"},
        campusInvolvements: {"President": "Undergraduate Business Association", "Internal Relations Director": "Undergraduate Business Association", "Associate Consultant": "SCNO"},
        interests: ["Tennis", "Bouldering", "Video Games"],
        whyLPN: "I joined LPN because I wanted to develop professionally and because of the emphasis they place on giving back to the community. To me, LPN is a supportive community full of inspiring people that push me to be the best version of myself.",
        img: require("../../../../assets/actives/brothers/Stephen_Minn.jpg")
    },
    Tiffany_Wong: {
        class: "Kappa",
        homeTown: "Fremont, CA",
        major: "Business Administration",
        minor: "",
        emphasis: "Accounting, Finance",
        year: "4th",
        linkedIn: "https://linkedin.com/in/tiffanylwong/",
        practice: "Audit, Finance",
        pronouns: "She/Her/Hers",
        interests: ["Cooking", "Sports", "Hiking"],
        experience: {"Global Finance & Business Management Summer Analyst": "JPMorgan Chase & Co.", "Tax Intern": "KPMG", "FTMBA Program Student Assistant": "The Paul Merage School of Business","Finance & Revenue Services Intern":"City of Redwood City"},
        campusInvolvements: {"Vice President": "Beta Alpha Psi", "Athletics Intern": "Associated Students of UCI", "Representative": "Merage Undergraduate Student Association"},
        whyLPN: "After seeing so many inspiring brothers getting involved in the business community and giving back to the younger generation, I was motivated to step outside of my comfort zone and come out to LPN during my first year. This was the best decision I made in college so far and upon joining, I quickly realized that LPN is more than just another business organization on campus. It's a family away from home, and I'm so grateful to have such a strong support system and be surrounded by so many driven people who push me to become a better version of myself everyday. ",
        img: require("../../../../assets/actives/brothers/Tiffany_Wong.jpg")
    },

    // Mu
    Faith_Chia: {
        linkedIn: "https://www.linkedin.com/in/faith-chia/",
        homeTown: "Irvine, CA",
        year: "3rd",
        pronouns: "She/Her/Hers",
        class: "Mu",
        major: "Business Administration",
        minor: "Psychological Science",
        emphasis: "Marketing",
        practice: "Marketing, Merchandising",
        experience: {"Merchandising Intern": "The TJX Companies, Inc.", 'Admissions Student Assistant': "Merage Fully Employed MBA Program", "Marketing Representative": "Insomnia Cookies"},
        campusInvolvements: { "Executive Vice President": "Undergraduate Business Association", "Marketing Director": "Undergraduate Business Association","CTO":"Lambda Phi Nu","Recruiter":"Lambda Phi Nu","Associate Auditor":"Lambda Phi Nu", "Member": "Asian American Christian Fellowship"},
        interests: ["Fashion", "Thrifting","Beauty", "K-pop", "Anime","APEX Legends", "Animal watching", "Slime", "Traveling", "Trying new foods"],
        whyLPN: "Coming into college with almost no business experience, I wanted to not only find direction professionally, but also form meaningful relationships. Especially since Irvine is my hometown, I made it my goal to quickly become involved on campus and to maximize my college experience during my first year by pushing myself outside of my comfort zone. Joining LPN has proven to be one of the best decisions I made at UCI. LPN has truly been my home at UCI and has opened the door for me to explore leadership positions and professionalism opportunities that I never would have pursued before. I am extremely grateful for my warm, driven, supportive, and fun community and everything it's given me!",
        img: require("../../../../assets/actives/brothers/Faith_Chia.jpg")
    },
    
    Sera_Xu: {
        linkedIn: "https://www.linkedin.com/in/ziqing-sera-xu/",
        homeTown: "Wuhan, Hubei",
        year: "3rd",
        class: "Mu",
        major: "Business Economics",
        minor: "",
        emphasis: "Accounting",
        practice: "Audit",
        pronouns: "She/Her/Hers",
        experience: {"Assurance Intern":"PwC","Analyst Intern": "Taylor Stewart", "Student Assistant": "UC Irvine"},
        campusInvolvements: {"Advisor": "International Student Business Association","Member":"180 Degree Consulting"},
        interests: ["Meditation", "Hiking"],
        whyLPN: "LPN is a great place to be if you are ambitious and eager to explore the business world. There are a lot of great people working in different fields that can help us to seek what we really want to do. More so, I love to spend time with those interesting people. It is always a great time to hang out with them. ",
        img: require("../../../../assets/actives/brothers/Sera_Xu.jpg")
    },
    Josh_Tong: {
        linkedIn: "https://www.linkedin.com/in/jjtong1/",
        homeTown: "Hacienda Heights, CA",
        year: "4th",
        class: "Mu",
        major: "Business Administration",
        minor: "Digital Filmmaking",
        emphasis: "Marketing, Organization & Management",
        practice: "Marketing",
        pronouns: "He/Him/His",
        experience: {"Employer Branding Intern":"Skechers","Marketing Intern": "United Exchange Corporation", "Marketing & Content Intern": "DiverseVC", "Marketing Assistant": "Anteater Recreation Center"},
        campusInvolvements: {"Media & Technology Commissioner":"Associated Students of UCI","Content Creation Commissioner": "Associated Students of UCI", "VP of Technology": "Merage Undergraduate Student Association", "Mentor": "Management Information Student Society","Associate Counselor":"Lambda Phi Nu","Culture & Relationships Director":"Lambda Phi Nu"},
        interests: ["Weightlifting", "Snowboarding", "Basketball", "Protein", "Filmmaking", "Rock Watching"],
        whyLPN: "Group of professionals who thrive to excel in the professional world but also a group of people who like to have fun :)",
        img: require("../../../../assets/actives/brothers/Josh_Tong.jpg")
    },
    Linda_Woo: {
        linkedIn: "https://linkedin.com/in/lindawoo",
        homeTown: "San Gabriel, CA",
        year: "4th",
        class: "Mu",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Advisory",
        pronouns: "She/Her/Hers",
        experience: {"Marketing and Operations Intern":"ENGIE North America","Marketing Intern": "Cali Raw Nutrition", "Advisory Intern": "KPMG", "Program Assistant": "UC Irvine", },
        campusInvolvements: {"President": "Phi Zeta Tau"},
        interests: ["Binging Netflix", "Collecting stationary", "Grocery shopping"],
        whyLPN: "LPN is an organization that has encouraged, pushed, and challenged me to build myself up to the best possible version of myself. I am extremely grateful for all the relationships, memories, and support I’ve received from brothers of LPN I’ve meet this past year; they all have truly changed my college experience for the better and gave me the opportunity to take charge of my career path. I can wholeheartedly say joining LPN was the best decision of college thus far and I encourage everyone to come checkout what makes us so special.",
        img: require("../../../../assets/actives/brothers/Linda_Woo.jpg")
    },
   
    // Xi
    Sahana_Vairavaraj: {
        linkedIn: "https://www.linkedin.com/in/sahana-vairavaraj",
        homeTown: "Cypress, CA",
        year: "4th",
        class: "Mu",
        major: "Business Administration",
        minor: "English, Political Science",
        emphasis: "Accounting",
        practice: "Tax, Human Resources",
        pronouns: "She/Her/Hers",
        experience: {"Human Resources Intern":"Boys & Girls Club of Garden Grove","Human Resources  Intern": "Capital One", "Assurance Intern": "Marcum", "Assistant Director":"Mathnasium"},
        campusInvolvements: {"Member": "Human Resources Management Association"},
        interests: ["Karaoke", "Reading", "NBA (Warriors!)"],
        whyLPN: "I love LPN because there's so many different people, but the one thing that connects us all is a real passion for giving back and a drive to be constantly challenge ourselves. LPN has always reminded me that I shouldn't settle, whether it be in my career or my life, and I'm so grateful to everyone that pushes me to fight for what I want out of life.",
        img: require("../../../../assets/actives/brothers/Sahana_Vairavaraj.jpg")
    },
    Catherine_Lin: {
        linkedIn: "https://www.linkedin.com/in/catherineylin/",
        homeTown: "",
        year: "4th",
        class: "Xi",
        major: "Business Information Management",
        minor: "",
        emphasis: "",
        practice: "Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Marketing & Partnerships Student Associate":"Madison Square Garden Entertainment","Marketing & Partnerships Intern":"Counter Logic Gaming","Brand Ambassador":"Discord","Influencer Marketing Intern": "RISE Esports","Influencer Marketing (Partner Program)":"HyperX", "Stream Production Intern": "UCI Esports"},
        campusInvolvements: {"Member":"The Association of Gamers at UCI"},
        interests: ["Streaming", "Video Games", "Cosplay", "Badminton", "Cooking", "Art"],
        whyLPN: "I struggled to find a community where I felt like I belonged in college. Although I made a few friends in freshman year during week one, we slowly became distant as we all branched off to join different organizations on campus. I wanted to find a group of people I could relate to and create long lasting, memorable friendships. And that's exactly what I found in Lambda Phi Nu! I was able to create bonds with my fellow brothers, and I felt a real sense of belonging that I had never felt before at UCI.",
        img: require("../../../../assets/actives/brothers/Catherine_Lin.jpg")
    },
    Ian_Han: {
        linkedIn: "https://www.linkedin.com/in/ianqhan",
        homeTown: "Alhambra, CA",
        year: "4th",
        class: "Xi",
        major: "Business Administration",
        minor: "",
        emphasis: "Marketing, Organization & Management",
        practice: "Marketing, Human Resources",
        pronouns: "He/Him/His",
        experience: {"Sales Intern":"Box","Human Capital Intern": "Sunwest Bank", "Marketing Intern": "Giant Union", "Digital Marketing Intern": "The Portal"},
        campusInvolvements: {"Winter Associate Educator 2022":"Lambda Phi Nu"},
        interests: ["Music production","Reading", "Surfing","Skating","Nature","Fitness","Tea"],
        whyLPN: "I wanted to find a new community/a sense of brotherhood and LPN gave me an opportunity to join a community filled with driven and like-minded individuals. It's motivated me to continuously strive for excellence and to give back to my community. Though I have to say, I am most appreciative of the lifelong relationships that I have fostered throughout my time with LPN.",
        img: require("../../../../assets/actives/brothers/Ian_Han.jpg")
    },
    Lucian_Liu: {
        class: "Xi",
        homeTown: "Irvine, CA",
        major: "Business Administration",
        minor: "",
        emphasis: "Finance, Accounting",
        year: "4th",
        linkedIn: "https://www.linkedin.com/in/lucian-liu/",
        practice: "Finance",
        pronouns: "He/Him/His",
        interests: ["Day Hikes", "Tennis", "Marvel", "Ice Skating", "Photography", "Ping Pong"],
        experience: {"Summer Investment Analyst":"Prudential Private Capital","Finance Intern": "Experian", "Associate Intern": "High Water Capital", "Investment Banking Intern": "ROTH Capital Partners"},
        campusInvolvements: {"President": "Undergraduate Finance Association", "CEO": "Lambda Phi Nu"},
        whyLPN: "I chose Lambda Phi Nu because I was looking for a community of driven individuals, but what I found was much more. This organization has been an integral part of my college experience, and I'm extremely grateful for the memories I've made with other brothers. I am glad that I came out because LPN is a place I can confidently call my second home. Regardless of background, LPN has been accepting and welcoming of all walks of life, and I've been fortunate to meet so many unique individuals!",
        img: require("../../../../assets/actives/brothers/Lucian_Liu.jpg")
    },
    Catherine_Nguyen: {
        linkedIn: "https://www.linkedin.com/in/catherine-nguyen7/",
        homeTown: "Huntington Beach, CA",
        year: "3rd",
        class: "Xi",
        major: "Business Administration, Sociology",
        minor: "",
        emphasis: "Marketing",
        practice: "Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Marketing Demand Generation Intern": "HashiCorp", "Sales & Marketing Coordinator": "ViaLoop", "Student Assistant": "Fully Employed & Executive MBA Office"},
        campusInvolvements: { "President": "Undergraduate Business Association", "VP of Academic Affairs": "Merage Undergraduate Student Association", "VP of Scholarship": "Panhellenic Association" },
        interests: ["Hiking", "Yoga", "Photography", "Vlogging", "Road Trips"],
        whyLPN: "When I reflect upon my college journey thus far, I can not pinpoint the exact moment I fell in love with LPN. From early LA road-trips to studying until 4AM together, the achievements and adversities alike have undoubtedly shaped me into the Brother and leader I am today. While the fast-paced and competitive nature of business is stressful, LPN has provided me with the most authentic, transparent, and genuine community. To me, LPN is an irreplaceable family with individuals who wholeheartedly believe in each other and encourage one another to grow professionally and personally each day.",
        img: require("../../../../assets/actives/brothers/Catherine_Nguyen.jpg")
    },
    
    Omar_Naji: {
        linkedIn: "https://www.linkedin.com/in/omaranaji/",
        homeTown: "Diamond Bar, CA",
        year: "3rd",
        class: "Xi",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Human Resources",
        pronouns: "He/Him/His",
        experience: {"Talent Acquisition Intern": "TikTok", "Marketing Strategy Intern": "NUDA Juice & Wellness Shop", "Head Marketing Intern": "Dance4Joy Ministries"},
        campusInvolvements: {"VP of Membership": "Human Resources Management Association", "VP of Community Development": "Management Information Student Society", "Resident Advisor":"UCI Housing","Brand Ambassador": "Quokka Brew"},
        interests: ["Video games", "Sports", "Playing Trombone"],
        whyLPN: "Having been in ΛΦΝ for almost 2 years now, I can confidently say that this fraternity has completely shaped and solidified my personal and professional growth at college. As a first-year, I had no professional experience whatsoever. I was very overwhelmed, and I was struggling to find a community to call a home away from home. Lambda Phi Nu has given me those life-long friendships as well as a solid understanding of what I need to do to succeed in my life. I am forever in debt to this fraternity, and I hope to continue to give back to the business and UCI community as I have been given so much.",
        img: require("../../../../assets/actives/brothers/Omar_Naji.jpg")
    },
    Raymond_Dinh: {
        linkedIn: "https://www.linkedin.com/in/rdinh/",
        homeTown: "San Jose",
        year: "3rd",
        class: "Xi",
        major: "Business Administration",
        minor: "",
        emphasis: "",
        practice: "Project Management",
        pronouns: "He/Him/His",
        experience: {"eCommerce Market Analyst Intern": "HP", "Business Analyst Intern": "MENTOR Global Consulting", "Executive Intern": "Pathways to Career Success"},
        campusInvolvements: {"Phikeia Educator": "Phi Delta Theta", "Associate Educator": "Lambda Phi Nu", "Vice President of Internal Relations": "Merage Undergraduate Student Association"},
        interests: ["eCommerce", "Anime", "Rap culture", "Science", "Cooking", "EDM", "Basketball", "Social Justice"],
        whyLPN: "This fraternity is full of good people who excel at many kinds of things. The diversity of perspectives, careers, and aspirations really inspire me everyday . I’m here not because I’m a good person but because they make me want to be better everyday. Get inspired by those who are in LPN!",
        img: require("../../../../assets/actives/brothers/Raymond_Dinh.jpg")
    },
    Ryan_Miranda: {
        linkedIn: "https://www.linkedin.com/in/ryan-miranda-/",
        homeTown: "Cupertino, CA",
        year: "4th",
        class: "Xi",
        major: "Computer Science",
        minor: "",
        emphasis: "Intelligent Systems",
        practice: "Software Engineering",
        pronouns: "He/Him/His",
        experience: {"Software Engineer Intern ": "Microsoft", "Software Engineer Intern": "Vusar"},
        campusInvolvements: {"Exeuctive Vice President": "Management Information Student Society"},
        interests: ["Playing guitar", "Eating", "Peanut Butter", "TechCrunch", "Tesla"],
        whyLPN: "I came to LPN’s rush not knowing a single non-engineering student at UCI and without a solid group of friends. I was very introverted, but I wanted to meet new people from different majors and backgrounds than I was used to! I was amazed by how open every active brother was; no one tried to sell LPN to me. Instead, they talked about the amazing memories they had with the organization and the family they had found. After going through the pledging process with my amazing P-Bros, I I finally have a family of driven, passionate people who know how to have fun too!",
        img: require("../../../../assets/actives/brothers/Ryan_Miranda.jpg")
    },
   
    // Omicron
    Adrian_Siu: {
        linkedIn: "https://www.linkedin.com/in/adrianmsiu/",
        homeTown: "Millbrae, CA",
        year: "3rd",
        class: "Omicron",
        major: "Business Administration",
        minor: "",
        emphasis: "Marketing",
        practice: "Product Design",
        pronouns: "He/Him/His",
        experience: {"Marketing Intern":"Ingram Micro","Bobarista": "Urban Ritual Cafe", "Cashier": "Uni Souffle"},
        campusInvolvements: {"VP of Marketing Management": "Undergraduate Finance Association", "Assistant Director":"Associated Students of UCI", "Marketing Director": "Lambda Phi Nu"},
        interests: ["Major foodie", "Hanging with friends", "Photography", "Baking", "Cars"],
        whyLPN: "After my first year, I realized that the majority of my friends that I spoke to every day were STEM majors. Because of this, when I started to reflect on my first year, I noticed that I became extremely unmotivated to professionally grow and shape myself for my future endeavors. Whenever I tried to start applying to internships, my friends would not know how to edit my resume or prepare me for any interviews. This is what led me to sway away from them and not look into any positions. LPN allowed me to have a community of friends who I was able to come to with help regarding anything — whether it is business-related or not. They have pushed me to become more involved on-campus as well as in the adult world. Moreover, they have allowed me to open myself up to more people and become more confident in who I am.",
        img: require("../../../../assets/actives/brothers/Adrian_Siu.jpg")
    },
    Cathy_Yun: {
        linkedIn: "https://www.linkedin.com/in/cathylyun/",
        homeTown: "Buena Park, CA",
        year: "4th",
        class: "Omicron",
        major: "Business Economics",
        minor: "Accounting",
        emphasis: "",
        practice: "Tax",
        pronouns: "She/Her/Hers",
        experience: {"Tax Intern ": "Holthouse Carlin & Van Trigt", "Tax Intern": "BDO", "Campus Ambassador": "Becker Professional Education"},
        campusInvolvements: {"Vice President":"Beta Alpha Psi", "Director of Finance": "TEDxUCIrvine","Member":"Kappa Alpha Theta"},
        interests: ["Organizing", "Hydroponics", "Handmade crafts", "Disneyland", "Ice skating", "Health foods"],
        whyLPN: "I have learned so much from LPN brothers even before rushing, and I realized how genuine and selfless these individuals were. I never felt like I had to be someone else other than myself here. Friends are family that you can choose; LPN to me is the home I chose to thrive and belong in.",
        img: require("../../../../assets/actives/brothers/Cathy_Yun.jpg")
    },
    Haley_Kim: {
        linkedIn: "https://www.linkedin.com/in/haley-kim/",
        homeTown: "Irvine, CA",
        year: "3rd",
        class: "Omicron",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Finance",
        pronouns: "She/Her/Hers",
        experience: {"Incoming Corporate Banking Summer Analyst":"Wells Fargo","Customer Success Intern":"Crowdstrike","Managed Security Services Prodiver Intern": "BlackBerry", "Strategy Consulting Intern": "Sizigi"},
        campusInvolvements: { "VP of Finance": "Management Information Student Society", "VP of Corporate Relations": "Undergraduate Finance Association", "Recruiter": "Lambda Phi Nu"},
        interests: ["Skiing","Hot Yoga","Online Shopping"],
        whyLPN: "Coming into college as a math major, there was no sense of community. After going through pledging and getting to meet motivated people, I already felt the sense of community that I was looking for in my college experience.",
        img: require("../../../../assets/actives/brothers/Haley_Kim.jpg")
    },
    Jennifer_Lin: {
        linkedIn: "https://www.linkedin.com/in/chia-chenjenniferlin/",
        homeTown: "Fullerton, CA",
        year: "3rd",
        class: "Omicron",
        major: "Psychology, Sociology",
        minor: "Management",
        emphasis: "",
        practice: "Human Resources",
        pronouns: "She/Her/Hers",
        experience: {"Assessment & Innovation Intern":"UCI Center for Student Leadership","Social Media Marketing Intern":"vee-com","K-12 Math Tutor": "Our Place Healing Hearts Foundation", "HR Intern & Executive Assistant": "Alamo Inn & Suites", "Summer Intern": "Orange Country Social Services Agency"},
        campusInvolvements: {"VP of Operations": "Human Resources Management Association","Culture & Relations Director":"Lambda Phi Nu","Fall Term Recruiter":"Lambda Phi Nu"},
        interests: ["Singing", "Ukulele", "Guitar", "Piano", "Hiking", "Outdoor activities", "Painting", "Drawing", "Basketball", "Coffee & Boba"],
        whyLPN: "I first rushed LPN because I was interested in business and want to learn more about it. I was impressed by the accomplishments and the opportunities LPN has to offer.However, there are more to that.After speaking with the Active brothers and getting to know LPN's core values and mission statement, I truly want to be a part of this welcoming community. Moreover, the brothers of LPN are super hardworking and humble which inspires me to do the same. I am still new to LPN, but I cannot wait for more LPN memories and give back to the UCI community.",
        img: require("../../../../assets/actives/brothers/Jennifer_Lin.jpg")
    },
    Julio_Cano: {
        linkedIn: "https://www.linkedin.com/in/julioccano/",
        homeTown: "Los Angeles, CA",
        year: "3rd",
        class: "Omicron",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Marketing Strategy",
        pronouns: "He/Him/His",
        experience: {"Intern": "Real Estate Association", "Marketing Intern": "Management Information Student Society"},
        campusInvolvements: {"Mentor": "Undergraduate/Undeclared Mentoring Program", "Scholarship Recipient": "Hispanic 100 Foundation"},
        interests: ["Running", "Swimming", "Badminton", "Hiking", "Skincare", "Cooking", "Digital Art"],
        whyLPN: "Family. Coming into UCI as a biology major and quickly realizing it was not the career for me was a very daunting experience. Hence a large majority of my friends were biology or non-business majors. As I finished my GE’s and began taking business-related courses, I found myself with no one to turn to or relate to. I then decided to seek a community that shared the same passion for business as I did, but instead, I not only found a community but a family. Lambda Phi Nu is filled with individuals who are committed, determined, and passionate about reaching their full potential, prompting one also to adopt those characteristics and become driven and motivated themselves.",
        img: require("../../../../assets/actives/brothers/Julio_Cano.jpg")
    },
    Kaylie_Zhou: {
        linkedIn: "https://www.linkedin.com/in/kaylie-zhou/",
        homeTown: "San Gabriel, CA",
        year: "3rd",
        class: "Omicron",
        major: "Business Economics",
        minor: "Psychological Sciences",
        emphasis: "",
        practice: "Human Resources",
        pronouns: "She/Her/Hers",
        experience: {"Talent Acquisition Intern":"TikTok","Social Media Manager": "Twinkle Brown Sugar", "Human Resources Intern": "GaoTek Inc.", "Campus Ambassador": "The Economist"},
        campusInvolvements: { "Internal Auditor":"Lambda Phi Nu","VP of Professional Development":"Undergraduate Business Association","Marketing Strategy Associate Director":"Associated Students of UCI"},
        interests: ["Boba", "Disney", "Just Dance", "Window shopping"],
        whyLPN: "I came into UCI as an undeclared student with no idea what I wanted to do for my career. I wanted to be involved as much as possible on campus, but I did not know where to start. However, after finding LPN, I soon realized how inspirational everyone was and found myself wanting to be a leader—just like them. I know that joining LPN was the best decision I have made because I have learned so much and gained so many friends that I call my second family.",
        img: require("../../../../assets/actives/brothers/Kaylie_Zhou.jpg")
    },
    
    Naveen_Sastri: {
        linkedIn: "https://www.linkedin.com/in/naveen-dhillon-sastri/",
        homeTown: "Campbell, CA",
        year: "3rd",
        class: "Omicron",
        major: "Business Information Management",
        minor: "",
        emphasis: "",
        practice: "Marketing, Data Analytics",
        pronouns: "He/Him/His",
        experience: {"Marketing Planning Intern":"eBay", "Marketing Analytics Intern":"Workhap","Marketing & PR Intern": "Instaboost Media"},
        campusInvolvements: { "VP of Professional Development": "Undergraduate Business Association", "Historian Intern": "Tomo No Kai", "Culture Relations Director": "Lambda Phi Nu","Student Advisor and Finance Director":"BCEC","Finance & Analytics Director":"Marketing Association"},
        interests: ["Reading", "Watching TV", "Eating", "Going to the Beach", "Swimming" ],
        whyLPN: "I chose LPN because I wanted to grow, both professionally and personally. LPN has helped me achieve so much in the little time I have been a part of it. I view my class as my family. I view the other active members as close friends and mentors. LPN helps you in so many ways. Get involved and make the most of your time with LPN, because this tight-knit community is unlike any other.",
        img: require("../../../../assets/actives/brothers/Naveen_Sastri.jpg")
    },
    Jasraj_Singh: {
        linkedIn: "https://www.linkedin.com/in/jasrajsingh1/",
        homeTown: "Fremont, CA",
        year: "2nd",
        class: "Omicron",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Marketing",
        pronouns: "He/Him/His",
        experience: {"Content Marketer": "Sencha Credit", "IT Receptionist": "Pioneer Tax & Accounting Services Inc.", "Associate Employee": "Which Wich Superior Sandwiches"},
        campusInvolvements: {"External Affairs Intern": "Marketing Association", "Mentee": "Management Information Student Society"},
        interests: ["Anime", "Working out", "Basketball", "Gaming"],
        whyLPN: "I just came into UCI, and I had no idea what I wanted to do with my life and career. I always told myself that I wanted to be in the business field and wanted to be involved on campus. Since everything is online, I was extremely lost, and I was hunting for a source of motivation. Then I found LPN. Never in my life have I seen a group of individuals as motivated as the brothers in LPN. Everyone in this fraternity is so involved on campus and honestly serves as a role model in my life. I have already been finding out so much about myself socially and professionally, and I owe it all to LPN. I am glad to say that I have found my family in college.",
        img: require("../../../../assets/actives/brothers/Raj_Singh.jpg")
    },
    Vivian_Tran: {
        linkedIn: "https://www.linkedin.com/in/vivianltrvnn/",
        homeTown: "Elk Grove, CA",
        year: "2nd",
        class: "Omicron",
        major: "Business Administration",
        minor: "",
        emphasis: "",
        practice: "Human Resources, Marketing",
        pronouns: "She/Her/Hers",
        experience: {"People Development Intern":"Dow Jones","Talent Acquisition Intern":"Unifi","Digital Marketing Intern": "Kanerani"},
        campusInvolvements: { "VP of Community Development": "Merage Undergraduate Student Association", "VP of Outreach": "Human Resources Management Association"},
        interests: ["Impulse shopping", "Jamming out to music", "Chatting with friends"],
        whyLPN: "LPN gave me a community that pushes me to become the best version of myself and friends that I can call family. I know that no matter where I go I have endless encouragement and support.",
        img: require("../../../../assets/actives/brothers/Vivian_Tran.jpg")
    },
    Khoa_Tran: {
        linkedIn: "https://www.linkedin.com/in/khoattran/",
        homeTown: "Huntington Beach, CA",
        year: "4th",
        class: "Omicron",
        major: "Business Administration",
        minor: "",
        emphasis: "Finance, Information Systems",
        practice: "Finance",
        pronouns: "He/Him/His",
        experience: {"Middle Market Banking & Specialized Industries Summer Analyst": "JPMorgan Chase & Co.", "Legal Assistant": "Executive Park Law Offices"},
        campusInvolvements: {"Executive Vice President":"Undergraduate Finance Association", "Alumni Chair":"Anteater Ambassador Network"},
        interests: ["Surfing & Beach Activities", "Swimming", "Building Keyboards", "Going to the Driving Range"],
        whyLPN: "I chose LPN for the people and the community. I originally shied away from the business community as I believed it to be unsupportive, competitive, and unwelcoming. However, coming into LPN, I felt everyone's warmth as they accepted me and pushed me to become a better person. Along with all the growth I have made professionally, it has been amazing to have a group of people who I can just hang out with or eat with. The community has been amazing, and I cannot be thankful enough.",
        img: require("../../../../assets/actives/brothers/Khoa_Tran.jpg")
    },

    // Pi
    Courtney_Tsao: {
        linkedIn: "https://www.linkedin.com/in/courtney-tsao/",
        homeTown: "",
        year: "3rd",
        class: "Pi",
        major: "Business Economics, Sociology",
        minor: "",
        emphasis: "",
        practice: "Marketing Management",
        pronouns: "She/Her/Hers",
        experience: { "User Generated Content Intern":"Webtoon","Brand Management & PR Intern": "SoundOff Inc"},
        campusInvolvements: { "Vice President of Marketing": "Undergraduate Business Association", "Incoming Associate Counselor": "Lambda Phi Nu", "Vice President of Internal Affairs": "Marketing Association" },
        interests: "",
        whyLPN: "",
        img: require("../../../../assets/actives/brothers/Courtney_Tsao.jpg")
    },
    
    Hanui_Lee: {
        linkedIn: "https://www.linkedin.com/in/hanui-lee/",
        homeTown: "Berkeley, CA",
        year: "3rd",
        class: "Pi",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Product Design",
        pronouns: "She/Her/Hers",
        experience: {"UI/UX Intern":"Instaboost Media","Product Design Intern": "Roblox", "Intern": "Oracle Education Foundation"},
        campusInvolvements: {"VP of Fellowship": "Product @ UCI", },
        interests: "",
        whyLPN: "",
        img: require('../../../../assets/actives/brothers_small/Hanui_Lee.jpg')
    },
    Jamie_Zhao: {
        linkedIn: "https://www.linkedin.com/in/jamiezh/",
        homeTown: "San Francisco, CA",
        year: "2nd",
        class: "Pi",
        major: "Undeclared",
        minor: "",
        emphasis: "",
        practice: "Marketing",
        pronouns: "She/Her/Hers",
        experience: { "Social Media Intern":"Oigetit","Human Resources Intern":"UpCancer"},
        campusInvolvements: {"Member Relations Director":"Marketing Association","Recruiter - Winter Quarter":"Lambda Phi Nu"},
        interests: ["Dancing", "Video Games", "Reading"],
        whyLPN: "I choose Lambda Phi Nu because I felt lost and unsure of what to do with my future, so I pushed myself out of my comfort zone during quarantine to make new connections and strive to better myself professionally. I found all of that and more with Lambda Phi Nu. Not only did I make long-lasting connections, I found myself taking on internships and positions that I would never have imagined without LPN.",
        img: require('../../../../assets/actives/brothers_small/Jamie_Zhao.jpg')
    },
    Lilian_Luu: {
        linkedIn: "https://www.linkedin.com/in/lluu/",
        homeTown: "",
        year: "2nd",
        class: "Pi",
        major: "Business Administration",
        minor: "",
        emphasis: "",
        practice: "Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Social Media Ads Specialist Intern":"Instaboost Media","Executive MBA Admissions Student Assistant":"Paul Merage School of Business"},
        campusInvolvements: {"VP of Corporate Relations":"Undergraduate Business Association","Representative": "Merage Undergraduate Student Association","Information Associate":"Lambda Phi Nu"},
        interests: ["Disney", "Hiking", "Broadway Musicals", "Karaoke", "Cooking"],
        whyLPN: "I chose Lambda Phi Nu because of the memorable and unique connections I made with each person I spoke to at rush. These connections stemmed from our shared values of Integrity, Curiosity, Altruism, Relationships and Excellence. As cheesy as it sounds, I truly believe that these core values allowed me to form more instantaneous and genuine connections, which made me feel drawn to the community that LPN's brothers foster. Within each step of my professional and personal life, I can always count on my brothers to challenge and inspire me to grow forward. I only just recently joined this fraternity, but I have already learned so much about the business world and made irreplaceable memories!",
        img: require('../../../../assets/actives/brothers/Lilian_Luu.jpg')
    },
    Lumin_Oo: {
        linkedIn: "https://www.linkedin.com/in/luminoo/",
        homeTown: "Stockton, CA",
        year: "2nd",
        class: "Pi",
        major: "Business Administration",
        minor: "",
        emphasis: "",
        practice: "Marketing, Consulting",
        pronouns: "He/Him/His",
        experience: "",
        campusInvolvements: { "VP of Marketing":"Undergraduate Business Association","Alumni & Campus Relations Director":"Marketing Association","Representative 20-21": "Merage Undergraduate Student Association", },
        interests: ["Sports", "Music", "Traveling", "Food"],
        whyLPN: "Joining LPN has been one of the highlights of my first year in college! I am glad to be a part of a community that is very supportive and inspiring. LPN has also helped me explore new things and step out of my comfort zone, enabling me to continuously grow in all forms.",
        img: require("../../../../assets/actives/brothers/Lumin_Oo.jpg")
    },
    Rithu_Eswaramoorthy: {
        linkedIn: "https://www.linkedin.com/in/rithu-eswaramoorthy/",
        homeTown: "Cupertino, CA",
        year: "2nd",
        class: "Pi",
        major: "Computer Science",
        minor: "",
        emphasis: "",
        practice: "Software Engineering",
        pronouns: "She/Her/Hers",
        experience: {"Software Engineer Intern":"Vusar","Software Development":"Firstly"},
        campusInvolvements: {"Corporate Organizer":"Hack at UCI","Software Engineer": "MAISS Project Teams","Webmaster":"Lambda Phi Nu","Member":"Women in Information and Computer Science"},
        interests: ["Baking","Food","Hiking","Pinterest Boards"],
        whyLPN: "I chose LPN to expand my social circle and academic focus as a CS major. Even during the short period of time that I have been a part of LPN, I have been able to meet so many motivated and kind individuals who I am looking forward to grow with the rest of my college career.",
        img: require('../../../../assets/actives/brothers/Rithu_Eswaramoorthy.jpg')
    },
    Elizabeth_Chan: {
        linkedIn: "https://www.linkedin.com/in/elizabethbchan/",
        homeTown: "San Francisco, CA",
        year: "4th",
        class: "Pi",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Real Estate",
        pronouns: "She/Her/Hers",
        experience: { "Research Analyst Intern":"CBRE","Brokerage Operations Intern": "Side, Inc.", "Academic Community Excellence Programmer": "UCI Housing" },
        campusInvolvements: { "Winter Associate Counselor":"Lambda Phi Nu","Member":"UCI Dragon Boat","Member ":"Real Estate Association" },
        interests: ["Stretching", "Yelping", "Paddling", "Brawl Stars", "Board Games" ],
        whyLPN: "Thanks to LPN, I am provided with a nurturing environment that encourages me to grow professionally and chase the stars. This community is full of passionate people who inspire me to live my best life every day.",
        img: require('../../../../assets/actives/brothers_small/Elizabeth_Chan.jpg')
    },
    Ethan_Canavan: {
        linkedIn: "https://www.linkedin.com/in/ethancanavan/",
        homeTown: "",
        year: "4th",
        class: "Pi",
        major: "Business Administration",
        minor: "",
        emphasis: "Marketing, Information Systems",
        practice: "Product Marketing",
        pronouns: "He/Him/His",
        experience: {"Business Development Intern":"OCHIN, Inc.","Marketing and Project Manager": "Mucci Assessment & Development", "Sales Manager": "UCI Campus Recreation"},
        campusInvolvements: {"CFO":"Lambda Phi Nu","Mentor":"Management Information Student Society"},
        interests: ["Listening to Music", "Basketball", "Eating Food"],
        whyLPN: "LPN has provided me with the community that I felt I had lacked through my first two years at UCI. Through my time in the fraternity, I have been able to form meaningful relationships while being pushed to develop myself professionally. Overall, my time in LPN has been extremely rewarding, as it has helped me grow professionally while forming incredible friendships with people I never would have had the chance to meet before.",
        img: require("../../../../assets/actives/brothers/Ethan_Canavan.jpg")
    },

    //Rho
    Aaron_Lee: {
        linkedIn: "https://www.linkedin.com/in/kyngnlee/",
        homeTown: "Seoul, South Korea",
        year: "1st",
        class: "Rho",
        major: "Business Administration",
        minor: "",
        emphasis: "",
        practice: "Corporate Law",
        pronouns: "He/Him/His",
        experience: {},
        campusInvolvements: {"Executive Associate":"Lambda Phi Nu"},
        interests: ["Basketball", "Shoes", "Late night walks"],
        whyLPN: "I chose LPN because I wanted a family. LPN is where it inspires me to push myself to be the best. The brotherhood and nurturing environment from my class and active members helped me grow as a person, and professionally. In LPN, I found my best friends, mentor, role model, and family. I am happy to say that LPN is my new home.",
        img: require('../../../../assets/actives/brothers/Aaron_Lee.jpg')
    },
    Talia_Yip: {
        linkedIn: "https://www.linkedin.com/in/taliayip/",
        homeTown: "Arcadia, CA",
        year: "2nd",
        class: "Rho",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Audit",
        pronouns: "She/Her/Hers",
        experience: {"Dance Instructor":"United Spirit Association","Youth Instructor":"Chinese Christian Heralds Crusades"},
        campusInvolvements: {},
        interests: ["Dancing", "Disney", "Exploring new taco trucks"],
        whyLPN: "LPN was the first group of people I met at UC Irvine. Coming in as a second year during the pandemic, I had no idea how to navigate the business world or put myself out there. I chose LPN because the people were so welcoming and willing to lend a hand. Whether it is professionally or personally, I know that this group of individuals will support and guide me forever!",
        img: require('../../../../assets/actives/brothers/Talia_Yip.jpg')
    },
    Sydney_Yu: {
        linkedIn: "https://www.linkedin.com/in/sydneymyu/",
        homeTown: "Arcadia, CA",
        year: "2nd",
        class: "Rho",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Accounting",
        pronouns: "She/Her/Hers",
        experience: {},
        campusInvolvements: {},
        interests: ["Figure Skating", "Dance", "Upcycling Clothes", "Fashion", "Watching Movies"],
        whyLPN: "Coming into my first quarter on campus at UCI, my initial goal was to focus solely on my professional development. However, with LPN, I not only found a group of people that would motivate me to grow professionally, but would also push me to get out of my comfort zone. It is crazy to look back and see just how much I have grown since the start of the year. I have learned more in the span of 8 weeks than I have in my entire life and I know that my growth will only continue with the support of my fellow brothers.",
        img: require('../../../../assets/actives/brothers/Sydney_Yu.jpg')
    },
    Nicole_Nguyen: {
        linkedIn: "https://www.linkedin.com/in/nicolexn/",
        homeTown: "Saratoga, CA",
        year: "2nd",
        class: "Rho",
        major: "Business Administration",
        minor: "Information & Computer Science",
        emphasis: "Marketing & Finance",
        practice: "Marketing, Product Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Marketing Strategy Intern":"ASUCI Media & Technology","Intern":"Automobuild"},
        campusInvolvements: {"Co-VP of Fellowship":"Product Association","Representative":"Merage Undergraduate Student Association"},
        interests: ["Snowboarding", "Thrifting", "Shopping", "Running", "Hiking", "Reading", "Video Games"],
        whyLPN: "I chose LPN because of its emphasis on building relationships. Coming into my first in person and second year of college, I had yet to build a strong community on campus. LPN introduced me to that community. Over the last couple of months, LPN has taught me a new definition of friendship and family. I've grown so much professionally and personally throughout my time in LPN thus far, and I am so grateful for the relationships I have been able to develop.",
        img: require('../../../../assets/actives/brothers/Nicole_Nguyen.jpg')
    },
    Yllana_Casim: {
        linkedIn: "https://www.linkedin.com/in/yllanacasim/",
        homeTown: "San Diego, CA",
        year: "3rd",
        class: "Rho",
        major: "Business Economics",
        minor: "",
        emphasis: "Marketing",
        practice: "Marketing Strategy, Product Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Global Marketing Strategy Intern for IoT":"Ingram Micro","Campus Ambassador":"Course Hero","Sales and Marketing Specialist":"Nordstrom"},
        campusInvolvements: {"Co-VP of Community Development":"Management Information Student Society","Campus Outreach Leader":"TEDxUCIrvine","Consulting Apprentice":"Deloitte Diversity Mentorship Program","Second Tier Family Head":"Kababayan","General Member":"Pi Beta Phi"},
        interests: ["Skating", "Thrifting", "Sports", "Fixing cars", "Photoshoots", "TED talks", "Spotify playlists", "Singing", "Playing the piano"],
        whyLPN: "Before I joined LPN, the brothers I stayed connected with have been the most altruistic, kind, and supportive people I have met throughout college. I knew that I wanted to be part of an organization that is devoted to not only my self-growth, but are passionate about extending help to others outside the organization as well. I always learn something new through any LPN experience. LPN to me means having a tight-knit community of supportive and career-driven individuals. We are all collectively working together to achieve our own goals, whether it’s professional or personal. LPN has provided me with a family that I know I will stay connected with even after college.",
        img: require('../../../../assets/actives/brothers/Yllana_Casim.jpg')
    },
    Ashley_London: {
        linkedIn: "https://www.linkedin.com/in/ashley-london/",
        homeTown: "Burbank, CA",
        year: "3rd",
        class: "Rho",
        major: "Business Administration",
        minor: "",
        emphasis: "Finance, Marketing",
        practice: "Finance, Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Accounting Assistant":"Revolution Entertainment Services","Office Assistant":"Thorburn Chiropractic & Wellness Center"},
        campusInvolvements: {"Discussion Leader":"University Studies 1","Mentor":"Undergraduate/Undeclared Mentorship Program","Hall Representative":"Mesa Court City Council"},
        interests: ["All things Disney", "Thrifting", "Making Pinterest Boards", "Testing Out DIYs"],
        whyLPN: "I chose LPN because of its message to “Grow Froward. Give Back.” As someone who originally entered UCI as Undeclared, I faced many hardships on my path to switch majors into Business Administration. I wanted to ensure that I could help those that came after me within the undeclared community, and now it is my time to do so in the business community. Alongside this, I wanted to hit the ground running and push myself outside of my comfort zone. LPN has pushed me to become a version of myself I did not know was possible. I am so grateful for LPN because it has helped me continue to strive for bigger and better things, take initiative, and develop relationships that I treasure. The community here is extremely supportive and has helped me grow in so many aspects. LPN is a family that will support you and push you to further your development both professionally and personally.",
        img: require('../../../../assets/actives/brothers/Ashley_London.jpg')
    },
    Eddie_Rios: {
        linkedIn: "https://www.linkedin.com/in/eddierioss/",
        homeTown: "Los Angeles, CA",
        year: "1st",
        class: "Rho",
        major: "Business Administration",
        minor: "",
        emphasis: "Organization & Management",
        practice: "Consulting",
        pronouns: "He/Him/His",
        experience: {},
        campusInvolvements: {"Representative":"Merage Undergraduate Student Association"},
        interests: ["Roller skating", "Clothes shopping"],
        whyLPN: "To me, LPN means community. There’s an endless amount of people to be inspired by and always someone to back you up. LPN has opened my eyes to the opportunities that I otherwise would’ve missed out on. Through LPN, I was able to find the person I want to be, and I now have the resources to strive towards becoming that person.",
        img: require('../../../../assets/actives/brothers/Eddie_Rios.jpg')
    },
    Kayla_Wong: {
        linkedIn: "https://www.linkedin.com/in/hfkaylawong/",
        homeTown: "San Lorenzo, CA",
        year: "1st",
        class: "Rho",
        major: "Business Administration",
        minor: "",
        emphasis: "Marketing, Organization and Management",
        practice: "Marketing Management",
        pronouns: "She/Her/Hers",
        experience: {"Instructor":"Ms. Wei's Asian Cultural Dance Academy","International Project Coordinator":"Interact District 5170"},
        campusInvolvements: {"Representative":"Merage Undergraduate Student Association","Operations Associate":"Lambda Phi Nu"},
        interests: ["Dance", "Weightlifting", "Napping", "Eating ice", "Hanging out with my cat", "Slime"],
        whyLPN: "To me LPN is a safe space for me to grow and authentically be myself. Coming in as a first-year, I felt very lost when it came to starting my professional career. I was super overwhelmed which is why I initially rushed for LPN. After the first quarter, I have realized that what LPN has provided me is much more than just professional guidance. From LPN I have gained a new support system and family whom I love unconditionally.",
        img: require('../../../../assets/actives/brothers/Kayla_Wong.jpg')
    },

    // Sigma
    Deena_Toofan: {
        // linkedIn: "https://www.linkedin.com/in/hfkaylawong/",
        // homeTown: "San Lorenzo, CA",
        year: "3rd",
        class: "Sigma",
        major: "Business Administration",
        // minor: "",
        // emphasis: "Marketing, Organization and Management",
        // practice: "Marketing Management",
        // pronouns: "She/Her/Hers",
        // experience: {"Instructor":"Ms. Wei's Asian Cultural Dance Academy","International Project Coordinator":"Interact District 5170"},
        // campusInvolvements: {"Representative":"Merage Undergraduate Student Association","Operations Associate":"Lambda Phi Nu"},
        // interests: ["Dance", "Weightlifting", "Napping", "Eating ice", "Hanging out with my cat", "Slime"],
        // whyLPN: "To me LPN is a safe space for me to grow and authentically be myself. Coming in as a first-year, I felt very lost when it came to starting my professional career. I was super overwhelmed which is why I initially rushed for LPN. After the first quarter, I have realized that what LPN has provided me is much more than just professional guidance. From LPN I have gained a new support system and family whom I love unconditionally.",
        img: require('../../../../assets/lpn_assets/pfp_temp.png'),
    },
    Hans_Chang: {
        // linkedIn: "https://www.linkedin.com/in/hfkaylawong/",
        // homeTown: "San Lorenzo, CA",
        year: "2nd",
        class: "Sigma",
        major: "Business Economics",
        // minor: "",
        // emphasis: "Marketing, Organization and Management",
        // practice: "Marketing Management",
        // pronouns: "She/Her/Hers",
        // experience: {"Instructor":"Ms. Wei's Asian Cultural Dance Academy","International Project Coordinator":"Interact District 5170"},
        // campusInvolvements: {"Representative":"Merage Undergraduate Student Association","Operations Associate":"Lambda Phi Nu"},
        // interests: ["Dance", "Weightlifting", "Napping", "Eating ice", "Hanging out with my cat", "Slime"],
        // whyLPN: "To me LPN is a safe space for me to grow and authentically be myself. Coming in as a first-year, I felt very lost when it came to starting my professional career. I was super overwhelmed which is why I initially rushed for LPN. After the first quarter, I have realized that what LPN has provided me is much more than just professional guidance. From LPN I have gained a new support system and family whom I love unconditionally.",
        img: require('../../../../assets/lpn_assets/pfp_temp.png'),
    },
    Jaejin_Kim: {
        // linkedIn: "https://www.linkedin.com/in/hfkaylawong/",
        // homeTown: "San Lorenzo, CA",
        year: "1st",
        class: "Sigma",
        major: "Computer Science",
        // minor: "",
        // emphasis: "Marketing, Organization and Management",
        // practice: "Marketing Management",
        // pronouns: "She/Her/Hers",
        // experience: {"Instructor":"Ms. Wei's Asian Cultural Dance Academy","International Project Coordinator":"Interact District 5170"},
        // campusInvolvements: {"Representative":"Merage Undergraduate Student Association","Operations Associate":"Lambda Phi Nu"},
        // interests: ["Dance", "Weightlifting", "Napping", "Eating ice", "Hanging out with my cat", "Slime"],
        // whyLPN: "To me LPN is a safe space for me to grow and authentically be myself. Coming in as a first-year, I felt very lost when it came to starting my professional career. I was super overwhelmed which is why I initially rushed for LPN. After the first quarter, I have realized that what LPN has provided me is much more than just professional guidance. From LPN I have gained a new support system and family whom I love unconditionally.",
        img: require('../../../../assets/lpn_assets/pfp_temp.png'),
    },
    Jodie_Tai: {
        // linkedIn: "https://www.linkedin.com/in/hfkaylawong/",
        // homeTown: "San Lorenzo, CA",
        year: "3rd",
        class: "Sigma",
        major: "Business Economics",
        // minor: "",
        // emphasis: "Marketing, Organization and Management",
        // practice: "Marketing Management",
        // pronouns: "She/Her/Hers",
        // experience: {"Instructor":"Ms. Wei's Asian Cultural Dance Academy","International Project Coordinator":"Interact District 5170"},
        // campusInvolvements: {"Representative":"Merage Undergraduate Student Association","Operations Associate":"Lambda Phi Nu"},
        // interests: ["Dance", "Weightlifting", "Napping", "Eating ice", "Hanging out with my cat", "Slime"],
        // whyLPN: "To me LPN is a safe space for me to grow and authentically be myself. Coming in as a first-year, I felt very lost when it came to starting my professional career. I was super overwhelmed which is why I initially rushed for LPN. After the first quarter, I have realized that what LPN has provided me is much more than just professional guidance. From LPN I have gained a new support system and family whom I love unconditionally.",
        img: require('../../../../assets/lpn_assets/pfp_temp.png'),
    },
    Julie_Hsieh: {
        // linkedIn: "https://www.linkedin.com/in/hfkaylawong/",
        // homeTown: "San Lorenzo, CA",
        year: "1st",
        class: "Sigma",
        major: "Undeclared",
        // minor: "",
        // emphasis: "Marketing, Organization and Management",
        // practice: "Marketing Management",
        // pronouns: "She/Her/Hers",
        // experience: {"Instructor":"Ms. Wei's Asian Cultural Dance Academy","International Project Coordinator":"Interact District 5170"},
        // campusInvolvements: {"Representative":"Merage Undergraduate Student Association","Operations Associate":"Lambda Phi Nu"},
        // interests: ["Dance", "Weightlifting", "Napping", "Eating ice", "Hanging out with my cat", "Slime"],
        // whyLPN: "To me LPN is a safe space for me to grow and authentically be myself. Coming in as a first-year, I felt very lost when it came to starting my professional career. I was super overwhelmed which is why I initially rushed for LPN. After the first quarter, I have realized that what LPN has provided me is much more than just professional guidance. From LPN I have gained a new support system and family whom I love unconditionally.",
        img: require('../../../../assets/lpn_assets/pfp_temp.png'),
    },
    Justin_Chao: {
        // linkedIn: "https://www.linkedin.com/in/hfkaylawong/",
        // homeTown: "San Lorenzo, CA",
        year: "1st",
        class: "Sigma",
        major: "Business Administration",
        // minor: "",
        // emphasis: "Marketing, Organization and Management",
        // practice: "Marketing Management",
        // pronouns: "She/Her/Hers",
        // experience: {"Instructor":"Ms. Wei's Asian Cultural Dance Academy","International Project Coordinator":"Interact District 5170"},
        // campusInvolvements: {"Representative":"Merage Undergraduate Student Association","Operations Associate":"Lambda Phi Nu"},
        // interests: ["Dance", "Weightlifting", "Napping", "Eating ice", "Hanging out with my cat", "Slime"],
        // whyLPN: "To me LPN is a safe space for me to grow and authentically be myself. Coming in as a first-year, I felt very lost when it came to starting my professional career. I was super overwhelmed which is why I initially rushed for LPN. After the first quarter, I have realized that what LPN has provided me is much more than just professional guidance. From LPN I have gained a new support system and family whom I love unconditionally.",
        img: require('../../../../assets/lpn_assets/pfp_temp.png'),
    },
    Ruby_Ko: {
        // linkedIn: "https://www.linkedin.com/in/hfkaylawong/",
        // homeTown: "San Lorenzo, CA",
        year: "1st",
        class: "Sigma",
        major: "Business Administration",
        // minor: "",
        // emphasis: "Marketing, Organization and Management",
        // practice: "Marketing Management",
        // pronouns: "She/Her/Hers",
        // experience: {"Instructor":"Ms. Wei's Asian Cultural Dance Academy","International Project Coordinator":"Interact District 5170"},
        // campusInvolvements: {"Representative":"Merage Undergraduate Student Association","Operations Associate":"Lambda Phi Nu"},
        // interests: ["Dance", "Weightlifting", "Napping", "Eating ice", "Hanging out with my cat", "Slime"],
        // whyLPN: "To me LPN is a safe space for me to grow and authentically be myself. Coming in as a first-year, I felt very lost when it came to starting my professional career. I was super overwhelmed which is why I initially rushed for LPN. After the first quarter, I have realized that what LPN has provided me is much more than just professional guidance. From LPN I have gained a new support system and family whom I love unconditionally.",
        img: require('../../../../assets/lpn_assets/pfp_temp.png'),
    },
    Qui_Hoang: {
        // linkedIn: "https://www.linkedin.com/in/hfkaylawong/",
        // homeTown: "San Lorenzo, CA",
        year: "2nd",
        class: "Sigma",
        major: "Business Administration",
        // minor: "",
        // emphasis: "Marketing, Organization and Management",
        // practice: "Marketing Management",
        // pronouns: "She/Her/Hers",
        // experience: {"Instructor":"Ms. Wei's Asian Cultural Dance Academy","International Project Coordinator":"Interact District 5170"},
        // campusInvolvements: {"Representative":"Merage Undergraduate Student Association","Operations Associate":"Lambda Phi Nu"},
        // interests: ["Dance", "Weightlifting", "Napping", "Eating ice", "Hanging out with my cat", "Slime"],
        // whyLPN: "To me LPN is a safe space for me to grow and authentically be myself. Coming in as a first-year, I felt very lost when it came to starting my professional career. I was super overwhelmed which is why I initially rushed for LPN. After the first quarter, I have realized that what LPN has provided me is much more than just professional guidance. From LPN I have gained a new support system and family whom I love unconditionally.",
        img: require('../../../../assets/lpn_assets/pfp_temp.png'),
    },
    Will_Bordessa: {
        // linkedIn: "https://www.linkedin.com/in/hfkaylawong/",
        // homeTown: "San Lorenzo, CA",
        year: "3rd",
        class: "Sigma",
        major: "Business Administration",
        // minor: "",
        // emphasis: "Marketing, Organization and Management",
        // practice: "Marketing Management",
        // pronouns: "She/Her/Hers",
        // experience: {"Instructor":"Ms. Wei's Asian Cultural Dance Academy","International Project Coordinator":"Interact District 5170"},
        // campusInvolvements: {"Representative":"Merage Undergraduate Student Association","Operations Associate":"Lambda Phi Nu"},
        // interests: ["Dance", "Weightlifting", "Napping", "Eating ice", "Hanging out with my cat", "Slime"],
        // whyLPN: "To me LPN is a safe space for me to grow and authentically be myself. Coming in as a first-year, I felt very lost when it came to starting my professional career. I was super overwhelmed which is why I initially rushed for LPN. After the first quarter, I have realized that what LPN has provided me is much more than just professional guidance. From LPN I have gained a new support system and family whom I love unconditionally.",
        img: require('../../../../assets/lpn_assets/pfp_temp.png'),
    },

};

export default { profiles };