export const profiles = {
    // Mu
    Faith_Chia: {
        linkedIn: "https://www.linkedin.com/in/faith-chia/",
        homeTown: "Irvine, CA",
        year: "4th",
        pronouns: "She/Her/Hers",
        class: "Mu",
        major: "Business Administration",
        minor: "Psychological Science",
        emphasis: "Marketing, Organization & Management",
        practice: "Product Marketing, Merchandising",
        experience: {"Product Marketing Intern":"ServiceNow","Merchandising Intern": "The TJX Companies, Inc.", 'Admissions Student Assistant': "Merage Fully Employed MBA Program", "Marketing Representative": "Insomnia Cookies"},
        campusInvolvements: {"CEO":"Lambda Phi Nu", "Executive Vice President": "Undergraduate Business Association", "Marketing Director": "Undergraduate Business Association","CTO":"Lambda Phi Nu","Recruiter":"Lambda Phi Nu","Associate Auditor":"Lambda Phi Nu", "Member": "Asian American Christian Fellowship"},
        interests: ["Fashion", "Thrifting","Beauty", "K-pop", "Anime", "Manga/Manhaw","Games(Video, Word, Card, and Board)", "Skiing","Eating"],
        whyLPN: "Coming into college with almost no business experience, I wanted to not only find direction professionally, but also find a community. Joining LPN during my first quarter at UCI has proven to be one of the best decisions I made at UCI. LPN has given me professional skills, confidence, and an amazing community that I am so thankful to be a part of. It's been my home at UCI and has encouraged me to take on career/leadership positions and embody our motto of \"grow forward, give back.\" Most importantly, I treasure all the friendships I've made so far and look forward to the future ones to come!",
        img: require("../../../../assets/actives/brothers/Faith_Chia.jpg")
    },
    Sera_Xu: {
        linkedIn: "https://www.linkedin.com/in/ziqing-sera-xu/",
        homeTown: "Wuhan, Hubei",
        year: "4th",
        class: "Mu",
        major: "Business Economics",
        minor: "",
        emphasis: "Accounting",
        practice: "Consulting (Management / Tech) ",
        pronouns: "She/Her/Hers",
        experience: {"Business Operations":"Glassdoor","Assurance Intern":"PwC","Analyst Intern": "Taylor Stewart", "Student Assistant": "UC Irvine"},
        campusInvolvements: {"External Vice President":"180 Degree Consulting", "Member":"180 Degree Consulting", "Advisor": "International Student Business Association",},
        interests: ["Meditation", "Hiking"],
        whyLPN: "LPN is a great place to be if you are ambitious and eager to explore the business world. There are a lot of great people working in different fields that can help us to seek what we really want to do. More so, I love to spend time with those interesting people. It is always a great time to hang out with them. ",
        img: require("../../../../assets/actives/brothers/Sera_Xu.jpg")
    },
    
    // Xi
    Catherine_Lin: {
        linkedIn: "https://www.linkedin.com/in/catherineylin/",
        homeTown: "Fremont, CA",
        year: "4th",
        class: "Xi",
        major: "Business Economics",
        minor: "Business Economics",
        emphasis: "",
        practice: "Marketing, Social Media Management",
        pronouns: "She/Her/Hers",
        experience: {"Social Media Intern": "Team Liquid", "Marketing & Partnerships Student Associate":"Madison Square Garden Entertainment","Marketing & Partnerships Intern":"Counter Logic Gaming", "Influencer Marketing  (Partner Program)":"SUNNYD","Brand Ambassador":"Discord","Influencer Marketing Intern": "RISE Esports","Influencer Marketing (Partner Program)":"HyperX", "Stream Production Intern": "UCI Esports"},
        campusInvolvements: {"Member":"The Association of Gamers at UCI"},
        interests: ["Streaming", "Video Games", "Cosplay", "Badminton", "Cooking", "Art"],
        whyLPN: "I struggled to find a community where I felt like I belonged in college. Although I made a few friends in freshman year during week one, we slowly became distant as we all branched off to join different organizations on campus. I wanted to find a group of people I could relate to and create long lasting, memorable friendships. And that's exactly what I found in Lambda Phi Nu! I was able to create bonds with my fellow brothers, and I felt a real sense of belonging that I had never felt before at UCI.",
        img: require("../../../../assets/actives/brothers/Catherine_Lin.jpg")
    },
    Catherine_Nguyen: {
        linkedIn: "https://www.linkedin.com/in/catherine-nguyen7/",
        homeTown: "Huntington Beach, CA",
        year: "4th",
        class: "Xi",
        major: "Business Administration, Sociology",
        minor: "International Studies",
        emphasis: "Sales, Marketing",
        practice: "Marketing",
        pronouns: "She/Her/Hers",
        experience: {"AWS Sales Intern": "Amazon", "Marketing Demand Generation Intern": "HashiCorp", "Sales & Marketing Coordinator": "ViaLoop", "Student Assistant": "Fully Employed & Executive MBA Office"},
        campusInvolvements: { "President": "Undergraduate Business Association", "VP of Communications": "Merage Undergraduate Student Association", "VP of Academic Affairs": "Merage Undergraduate Student Association", "VP of Scholarship": "Panhellenic Association" },
        interests: ["Hiking", "Yoga", "Photography", "Vlogging", "Road Trips"],
        whyLPN: "When I reflect upon my college journey thus far, I can not pinpoint the exact moment I fell in love with LPN. From early LA road-trips to studying until 4AM together, the achievements and adversities alike have undoubtedly shaped me into the Brother and leader I am today. While the fast-paced and competitive nature of business is stressful, LPN has provided me with the most authentic, transparent, and genuine community. To me, LPN is an irreplaceable family with individuals who wholeheartedly believe in each other and encourage one another to grow professionally and personally each day.",
        img: require("../../../../assets/actives/brothers/Catherine_Nguyen.jpg")
    },
    
    Omar_Naji: {
        linkedIn: "https://www.linkedin.com/in/omaranaji/",
        homeTown: "Diamond Bar, CA",
        year: "4th",
        class: "Xi",
        major: "Business Economics, Sociology",
        minor: "",
        emphasis: "",
        practice: "Human Resources",
        pronouns: "He/Him/His",
        experience: {"Human Resources Intern": "Capital One","Talent Acquisition Intern": "TikTok", "Marketing Strategy Intern": "NUDA Juice & Wellness Shop", "Head Marketing Intern": "Dance4Joy Ministries"},
        campusInvolvements: {"Executive Vice President":"Management Information Student Society","VP of Community Development":"Management Information Student Society","Professional Development Intern":"Management  Information Student Society","Mentee":"Management  Information Student Society", "Associate Counseler":"Lambda Phi Nu", "Chief Talent Officer":"Lambda Phi Nu", "Recruiter":"Lambda Phi Nu", "Finance Associate":"Lambda Phi Nu","VP of Membership": "Human Resources Management Association","Intern": "Human Resources Management Association", "Resident Advisor":"UCI Housing","Brand Ambassador": "Quokka Brew"},
        interests: ["Concert", "Going Out", "Personal Development"],
        whyLPN: "LPN has truly defined my college experience, and I wouldn’t be the same.",
        img: require("../../../../assets/actives/brothers/Omar_Naji.jpg")
        
    },
    Raymond_Dinh: {
        linkedIn: "https://www.linkedin.com/in/rdinh/",
        homeTown: "San Jose",
        year: "4th",
        class: "Xi",
        major: "Business Administration",
        minor: "",
        emphasis: "Organization and Management",
        practice: "Technology Consulting, Business Analytics",
        pronouns: "He/Him/His",
        experience: {"Business Systems Analyst Intern":"Salesforce","eCommerce Market Analyst Intern": "HP", "Business Analyst Intern": "MENTOR Global Consulting", "Executive Intern": "Pathways to Career Success"},
        campusInvolvements: {"Vice President of Phi Delta Theta":"Phi Delta Theta","Phikeia Educator": "Phi Delta Theta", "Social Impact Director":"Lambda Phi Nu","Associate Educator": "Lambda Phi Nu", "Vice President of Internal Relations": "Merage Undergraduate Student Association"},
        interests: ["Working"],
        whyLPN: "Myself. They allowed me to grow so much, gave me my best college",
        img: require("../../../../assets/actives/brothers/Raymond_Dinh.jpg")
    },
    Ryan_Miranda: {
        linkedIn: "https://www.linkedin.com/in/ryan-miranda-/",
        homeTown: "Cupertino, CA",
        year: "2nd Year Graduate Student",
        class: "Xi",
        major: "M.S. in Computer Science",
        minor: "",
        emphasis: "",
        practice: "Software Engineering",
        pronouns: "He/Him/His",
        experience: {"Software Engineer Intern  ": "Microsoft  ", "Software Engineer Intern ": "Microsoft", "Software Engineer Intern ": "Microsoft", "Software   Engineer Intern": "Microsoft", "Software Engineer Intern": "Vusar"},
        campusInvolvements: {"Executive Vice President": "Management Information Student Society", "VP of Professional Development": "Management Information Student Society", "Professional Development Intern ": "Management Information Student Society","Fall Chief Talent Officer": "Lambda Phi Nu"},
        interests: ["Trying new foods", "Working out", "Cooking"],
        whyLPN: "LPN is a group of amazing people who never fail to bring out the best in myself. They allowed me to grow so much, gave me my favorite college memories, and are the reason I stayed another year at UCI!",
        img: require("../../../../assets/actives/brothers/Ryan_Miranda.jpg")
    },
   
    // Omicron
    Adrian_Siu: {
        linkedIn: "https://www.linkedin.com/in/adrianmsiu/",
        homeTown: "Millbrae, CA",
        year: "4th",
        class: "Omicron",
        major: "Business Administration",
        minor: "",
        emphasis: "Marketing",
        practice: "Marketing Analytics",
        pronouns: "He/Him/His",
        experience: {"Solutions Marketing Co-Op": "ServiceNow", "Marketing Intern":"Ingram Micro"},
        campusInvolvements: {"VP of Marketing Management": "Undergraduate Finance Association", "Associate Director of Technology":"Associated Students of UCI","Assistant Director":"Associated Students of UCI", "Marketing Director": "Lambda Phi Nu"},
        interests: ["Major foodie", "Hanging with friends", "Photography", "Baking", "Cars"],
        whyLPN: "After my first year, I realized that the majority of my friends that I spoke to every day were STEM majors. Because of this, when I started to reflect on my first year, I noticed that I became extremely unmotivated to professionally grow and shape myself for my future endeavors. Whenever I tried to start applying to internships, my friends would not know how to edit my resume or prepare me for any interviews. This is what led me to sway away from them and not look into any positions. LPN allowed me to have a community of friends who I was able to come to with help regarding anything — whether it is business-related or not. They have pushed me to become more involved on-campus as well as in the adult world. Moreover, they have allowed me to open myself up to more people and become more confident in who I am.",
        img: require("../../../../assets/actives/brothers/Adrian_Siu.jpg")
    },
    
    Haley_Kim: {
        linkedIn: "https://www.linkedin.com/in/haley-kim/",
        homeTown: "Irvine, CA",
        year: "3rd",
        class: "Omicron",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Finance",
        pronouns: "She/Her/Hers",
        experience: {"Incoming Corporate Banking Summer Analyst":"Wells Fargo","Customer Success Intern":"Crowdstrike","Managed Security Services Prodiver Intern": "BlackBerry", "Strategy Consulting Intern": "Sizigi"},
        campusInvolvements: { "VP of Finance": "Management Information Student Society", "VP of Corporate Relations": "Undergraduate Finance Association", "Recruiter": "Lambda Phi Nu"},
        interests: ["Skiing","Hot Yoga","Online Shopping"],
        whyLPN: "Coming into college as a math major, there was no sense of community. After going through pledging and getting to meet motivated people, I already felt the sense of community that I was looking for in my college experience.",
        img: require("../../../../assets/actives/brothers/Haley_Kim.jpg")
    },
    Jennifer_Lin: {
        linkedIn: "https://www.linkedin.com/in/chia-chenjenniferlin/",
        homeTown: "Fullerton, CA",
        year: "3rd",
        class: "Omicron",
        major: "Psychology, Sociology",
        minor: "Management",
        emphasis: "",
        practice: "Human Resources",
        pronouns: "She/Her/Hers",
        experience: {"Assessment & Innovation Intern":"UCI Center for Student Leadership","Social Media Marketing Intern":"vee-com","K-12 Math Tutor": "Our Place Healing Hearts Foundation", "HR Intern & Executive Assistant": "Alamo Inn & Suites", "Summer Intern": "Orange Country Social Services Agency"},
        campusInvolvements: {"VP of Operations": "Human Resources Management Association","Culture & Relations Director":"Lambda Phi Nu","Fall Term Recruiter":"Lambda Phi Nu"},
        interests: ["Singing", "Ukulele", "Guitar", "Piano", "Hiking", "Outdoor activities", "Painting", "Drawing", "Basketball", "Coffee & Boba"],
        whyLPN: "I first rushed LPN because I was interested in business and want to learn more about it. I was impressed by the accomplishments and the opportunities LPN has to offer.However, there are more to that.After speaking with the Active brothers and getting to know LPN's core values and mission statement, I truly want to be a part of this welcoming community. Moreover, the brothers of LPN are super hardworking and humble which inspires me to do the same. I am still new to LPN, but I cannot wait for more LPN memories and give back to the UCI community.",
        img: require("../../../../assets/actives/brothers/Jennifer_Lin.jpg")
    },
    Julio_Cano: {
        linkedIn: "https://www.linkedin.com/in/julioccano/",
        homeTown: "Los Angeles, CA",
        year: "4th",
        class: "Omicron",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Entrepreneurship, Strategic Marketing",
        pronouns: "He/Him/His",
        experience: {"Resident Advisor": "UCI Housing", "Client Associate": "Julio's Jewelry Repair and Design", "Intern": "Real Estate Association", "Marketing Intern": "Management Information Student Society"},
        campusInvolvements: {"Mentor": "Undergraduate/Undeclared Mentoring Program", "Marketing Intern": "Management Information Student Society", "Marketing  Intern": "Real Estate Association"},
        interests: ["Running", "Swimming", "Badminton", "Hiking", "Skincare", "Cooking", "Digital Art"],
        whyLPN: "Family. Coming into UCI as a biology major and quickly realizing it was not the career for me was a very daunting experience. Hence a large majority of my friends were biology or non-business majors. As I finished my GE’s and began taking business-related courses, I found myself with no one to turn to or relate to. I then decided to seek a community that shared the same passion for business as I did, but instead, I not only found a community but a family. Lambda Phi Nu is filled with individuals who are committed, determined, and passionate about reaching their full potential, prompting one also to adopt those characteristics and become driven and motivated themselves.",
        img: require("../../../../assets/actives/brothers/Julio_Cano.jpg")
    },
    Kaylie_Zhou: {
        linkedIn: "https://www.linkedin.com/in/kaylie-zhou/",
        homeTown: "San Gabriel, CA",
        year: "4th",
        class: "Omicron",
        major: "Business Economics",
        minor: "Psychological Sciences",
        emphasis: "",
        practice: "Human Resources",
        pronouns: "She/Her/Hers",
        experience: {"Global Rewards Intern":"Adobe", "Talent Acquisition Intern":"TikTok","Social Media Manager": "Twinkle Brown Sugar", "Human Resources Intern": "GaoTek Inc.", "Campus Ambassador": "The Economist"},
        campusInvolvements: { "Internal Auditor":"Lambda Phi Nu","VP of Professional Development":"Undergraduate Business Association","Marketing Strategy Associate Director":"Associated Students of UCI"},
        interests: ["Boba", "Disney", "Just Dance", "Window shopping"],
        whyLPN: "I came into UCI as an undeclared student with no idea what I wanted to do for my career. I wanted to be involved as much as possible on campus, but I did not know where to start. However, after finding LPN, I soon realized how inspirational everyone was and found myself wanting to be a leader—just like them. I know that joining LPN was the best decision I have made because I have learned so much and gained so many friends that I call my second family.",
        img: require("../../../../assets/actives/brothers/Kaylie_Zhou.jpg")
    },
    Naveen_Sastri: {
        linkedIn: "https://www.linkedin.com/in/naveen-dhillon-sastri/",
        homeTown: "Campbell, CA",
        year: "4th",
        class: "Omicron",
        major: "Business Information Management",
        minor: "",
        emphasis: "",
        practice: "Marketing, Data Analytics, Product",
        pronouns: "He/Him/His",
        experience: {"Cyber & Intelligence Solutions Intern":"Mastercard", "Data Analytics Intern":"eBay", "Marketing Analytics Intern":"Workhap","SEO Marketing Intern": "Instaboost Media"},
        campusInvolvements: { "President":"Undergraduate Business Association", "VP of Professional Development": "Undergraduate Business Association", "Co-President":"Marketing Association", "Culture Relations Director": "Lambda Phi Nu","Student Advisor and Finance Director":"BCEC","Finance & Analytics Director":"Marketing Association"},
        interests: ["Tennis","Listening to music","Eating","Watching TV","Talking"],
        whyLPN: "LPN is my motivation and my family. My resume would be blank and, I would have not pursued a career in business without it. I would not have pushed myself to do what I’m doing now. I owe a lot to this fraternity, and I would do anything to make sure that this organization thrives. But more than anything, I found a community in LPN.",
        img: require("../../../../assets/actives/brothers/Naveen_Sastri.jpg")
    },
    Jasraj_Singh: {
        linkedIn: "https://www.linkedin.com/in/jasrajsingh1/",
        homeTown: "Fremont, CA",
        year: "3rd",
        class: "Omicron",
        major: "Business Economics",
        minor: "Psychology",
        emphasis: "Entrepreneurship",
        practice: "Marketing",
        pronouns: "He/Him/His",
        experience: {"CEO": "Ess Dee Consulting Inc", "Content Marketer": "Sencha Credit", "IT Receptionist": "Pioneer Tax & Accounting Services Inc.", "Associate Employee": "Which Wich Superior Sandwiches"},
        campusInvolvements: {"External Affairs Intern": "Marketing Association", "Mentee": "Management Information Student Society"},
        interests: ["Anime", "Working out", "Basketball", "Gaming"],
        whyLPN: "I just came into UCI, and I had no idea what I wanted to do with my life and career. I always told myself that I wanted to be in the business field and wanted to be involved on campus. Since everything is online, I was extremely lost, and I was hunting for a source of motivation. Then I found LPN. Never in my life have I seen a group of individuals as motivated as the brothers in LPN. Everyone in this fraternity is so involved on campus and honestly serves as a role model in my life. I have already been finding out so much about myself socially and professionally, and I owe it all to LPN. I am glad to say that I have found my family in college.",
        img: require("../../../../assets/actives/brothers/Raj_Singh.jpg")
    },
    Vivian_Tran: {
        linkedIn: "https://www.linkedin.com/in/vivianltrvnn/",
        homeTown: "Elk Grove, CA",
        year: "2nd",
        class: "Omicron",
        major: "Business Administration",
        minor: "Psychological Science ",
        emphasis: "Organization and Management",
        practice: "Project Management",
        pronouns: "She/Her/Hers",
        experience: {"IT Project Management Intern":"ServiceNow", "People Development Intern":"Dow Jones","Talent Acquisition Intern":"Unifi","Digital Marketing Intern": "Kanerani"},
        campusInvolvements: {"VP of Graduate and Alumni Relations": "Merage Undergraduate Student Association", "VP of Community Development": "Merage Undergraduate Student Association", "VP of Outreach": "Human Resources Management Association"},
        interests: ["Playing overcooked","Tennis","Carpool Karaoke"],
        whyLPN: "LPN gave me a community that pushes me to become the best version of myself and friends that I can call family. I know that no matter where I go I have endless encouragement and support.",
        img: require("../../../../assets/actives/brothers/Vivian_Tran.jpg")
    },
 
    // Pi
    Courtney_Tsao: {
        linkedIn: "https://www.linkedin.com/in/courtney-tsao/",
        homeTown: "San Gabriel, CA",
        year: "4th",
        class: "Pi",
        major: "Business Economics, Sociology",
        minor: "",
        emphasis: "",
        practice: "Marketing Strategy",
        pronouns: "She/Her/Hers",
        experience: {"Consumer Insights Intern":"NBCUniversal","User Generated Content Intern":"Webtoon","Brand Management & PR Intern": "SoundOff Inc", "Marketing Strategy Intern":"Associated Students of UCI"},
        campusInvolvements: { "Vice President of Marketing": "Undergraduate Business Association", "Associate Counselor": "Lambda Phi Nu", "Vice President of Internal Affairs": "Marketing Association" },
        interests: ["Gymming","Anime","Cooking","Visiting Aquariums","Trying new cafes"],
        whyLPN: "LPN has given me the opportunity to find a group of friends I can rely on for support and professional development. I'm super grateful to have found such an inspirational community that motivates me to continue growing.",
        img: require("../../../../assets/actives/brothers/Courtney_Tsao.jpg")
    },
    
    Hanui_Lee: {
        linkedIn: "https://www.linkedin.com/in/hanui-lee/",
        homeTown: "Berkeley, CA",
        year: "3rd",
        class: "Pi",
        major: "Business Economics",
        minor: "Digital Information Systems",
        emphasis: "",
        practice: "Product Design",
        pronouns: "She/Her/Hers",
        experience: {"Summer Design Analyst": "JP Morgan Chase & Co","Product Design Intern": "Roblox", "Intern": "Oracle Education Foundation"},
        campusInvolvements: {"Executive Vice President":"Product at UCI","VP of Fellowship": "Product @ UCI", "Associate Auditor": "Lambda Phi Nu",},
        interests: ["Cooking","Baking","Reading","Video Games","Swimming","Music","Fonts"],
        whyLPN: "Memories, and are the reason I'm staying another year at UCI!",
        img: require('../../../../assets/actives/brothers/Hanui_Lee.jpg')
    },
    Jamie_Zhao: {
        linkedIn: "https://www.linkedin.com/in/jamiezh/",
        homeTown: "San Francisco, CA",
        year: "3rd",
        class: "Pi",
        major: "Business Economics",
        minor: "Management",
        emphasis: "",
        practice: "Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Partnerships Intern":"UCI Esports", "Strategic Events Intern":"ServiceNow", "Social Media Intern":"Oigetit","Human Resources Intern":"UpCancer"},
        campusInvolvements: {"VP of External Affairs":"Management Information Student Society", "Member Relations Director":"Marketing Association","Recruiter - Winter Quarter":"Lambda Phi Nu"},
        interests: ["Dancing", "Video Games", "Trying out new foods"],
        whyLPN: "I chose to rush LPN because I really wanted to push myself out of my comfort zone. During my freshman year, I felt isolated and demotivated during quarantine. I wanted to push myself out of my slump by joining this fraternity that not only furthered myself professionally, but I also created so many connections that I treasure deeply. I know that I would not be where I am without LPN.",
        img: require('../../../../assets/actives/brothers/Jamie_Zhao.jpg')
    },
    Lilian_Luu: {
        linkedIn: "https://www.linkedin.com/in/lluu/",
        homeTown: "",
        year: "3rd",
        class: "Pi",
        major: "Business Administration",
        minor: "",
        emphasis: "Marketing",
        practice: "Public Relations, Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Public Relations Intern":"Comcast", "Social Media Ads Specialist Intern":"Instaboost Media","Executive MBA Admissions Student Assistant":"Paul Merage School of Business"},
        campusInvolvements: {"Executive Vice President":"Undergraduate Business Association","VP of Corporate Relations":"Undergraduate Business Association","Representative": "Merage Undergraduate Student Association","Information Associate":"Lambda Phi Nu"},
        interests: ["Cooking","Disney", "Skincare", "Carpool Karaoke", "Making Boba"],
        whyLPN: "LPN was my first community at UCI. All the brothers made me feel like I had a place and that connection has stuck. Professionally and personally, you won't find better coaches or cheerleaders to get you through the highs & lows. Ohana means family and no one gets left behind or forgotten here.",
        img: require('../../../../assets/actives/brothers/Lilian_Luu.jpg')
    },
    Lumin_Oo: {
        linkedIn: "https://www.linkedin.com/in/luminoo/",
        homeTown: "Stockton, CA",
        year: "3rd",
        class: "Pi",
        major: "Business Administration",
        minor: "",
        emphasis: "Organization & Management, Information Systems",
        practice: "Consulting",
        pronouns: "He/Him/His",
        experience: {"Discovery Consulting Intern":"Deloitte"},
        campusInvolvements: {"Vice President of Administration":"Undergraduate Business Association","VP of Marketing":"Undergraduate Business Association","Alumni & Campus Relations Director":"Marketing Association","Finance Director":"Lambda Phi Nu","Representative": "Merage Undergraduate Student Association", },
        interests: ["Sports", "Music", "Traveling", "Food", "Weightlifting"],
        whyLPN: "Joining LPN was one of the best decisions I made during my time in college. I am grateful to be a part of a community that is so supportive and inspiring. LPN has helped facilitate my growth both professionally and personally by enabling me to explore new things and step out of my comfort zone. The experiences I've gained and all the relationships I've formed are second to none.",
        img: require("../../../../assets/actives/brothers/Lumin_Oo.jpg")
    },
    Rithu_Eswaramoorthy: {
        linkedIn: "https://www.linkedin.com/in/rithu-eswaramoorthy/",
        homeTown: "Cupertino, CA",
        year: "3rd",
        class: "Pi",
        major: "Computer Science",
        minor: "",
        emphasis: "",
        practice: "Software Engineering",
        pronouns: "She/Her/Hers",
        experience: {"Software Engineer  Intern":"MongoDB","Software Engineer Intern":"Vusar","Software Development":"Firstly"},
        campusInvolvements: {"Corporate Organizer":"Hack at UCI","VP of Professional Development ": "MAISS","Software Engineer": "MAISS Project Teams","Webmaster":"Lambda Phi Nu","Member":"Women in Information and Computer Science"},
        interests: ["Baking","Food","Hiking","Pinterest Boards"],
        whyLPN: "I chose LPN to expand my social circle and academic focus as a CS major. Even during the short period of time that I have been a part of LPN, I have been able to meet so many motivated and kind individuals who I am looking forward to grow with the rest of my college career.",
        img: require('../../../../assets/actives/brothers/Rithu_Eswaramoorthy.jpg')
    },
    Liz_Chan: {
        linkedIn: "https://www.linkedin.com/in/elizabethbchan/",
        homeTown: "San Francisco, CA",
        year: "4th",
        class: "Pi",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Real Estate",
        pronouns: "She/Her/Hers",
        experience: {"Brokerage Intern":"CBRE", "Research Analyst Intern":"CBRE","Brokerage Operations Intern": "Side, Inc.", "Academic Community Excellence Programmer": "UCI Housing" },
        campusInvolvements: { "Winter Associate Counselor":"Lambda Phi Nu","Operations Associate":"Lambda Phi Nu", "Member":"UCI Dragon Boat","Director of Public Relations":"Real Estate Association","Vice President of Community Development":"Real Estate Association", "Vice President of Internal Affairs":"Women in Leadership" },
        interests: ["Stretching", "Yelping", "Paddling", "Crying", "Brawl Stars" ],
        whyLPN: "Thanks to LPN, I am provided with a nurturing environment that encourages me to grow professionally and chase the stars. This community is full of passionate people who inspire me to live my best life every day.",
        img: require('../../../../assets/actives/brothers/Liz_Chan.jpg')
    },

    //Rho
    Aaron_Lee: {
        linkedIn: "https://www.linkedin.com/in/kyngnlee/",
        homeTown: "Seoul, South Korea",
        year: "2nd",
        class: "Rho",
        major: "Business Administration",
        minor: "",
        emphasis: "Finance, Corporate Law",
        practice: "Finance",
        pronouns: "He/Him/His",
        experience: {"Student Assistant": "Paul Merage Financial Services ", "Finance Intern":"Oppti"},
        campusInvolvements: {"Executive Associate":"Lambda Phi Nu"},
        interests: ["Basketball", "Shoe Collecting"],
        whyLPN: "LPN gave me so much more than professionalism: friends, family, and unforgettable memories. LPN means home away from home to me, it always provides a secure place for me to thrive and try new things knowing every brother supports me.",
        img: require('../../../../assets/actives/brothers/Aaron_Lee.jpg')
    },
    Talia_Yip: {
        linkedIn: "https://www.linkedin.com/in/taliayip/",
        homeTown: "Arcadia, CA",
        year: "3rd",
        class: "Rho",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Audit",
        pronouns: "She/Her/Hers",
        experience: {"Incoming Audit Intern":"PWC", "Incoming  Audit Intern":"Deloitte", "Dance Instructor":"United Spirit Association"},
        campusInvolvements: {"External Vice President":"Accounting Association", "Recruiter":"Lambda Phi Nu","Finance Director":"Lambda Phi Nu"},
        interests: ["Dancing", "Disney", "Exploring new taco trucks"],
        whyLPN: "LPN was the first group of people I met at UC Irvine. Coming in as a second year during the pandemic, I had no idea how to navigate the business world or put myself out there. I chose LPN because the people were so welcoming and willing to lend a hand. Whether it is professionally or personally, I know that this group of individuals will support and guide me forever!",
        img: require('../../../../assets/actives/brothers/Talia_Yip.jpg')
    },
    Sydney_Yu: {
        linkedIn: "https://www.linkedin.com/in/sydneymyu/",
        homeTown: "Arcadia, CA",
        year: "3rd",
        class: "Rho",
        major: "Business Economics",
        minor: "Accounting",
        emphasis: "",
        practice: "Audit",
        pronouns: "She/Her/Hers",
        experience: {"Incoming Winter 2023  Audit intern":"EY", "Incoming Summer 2023 Audit  intern":"PwC"},
        campusInvolvements: {"Career Catalyst Director":"Lambda Phi Nu","Secretary":"Accounting Association"},
        interests: ["Figure Skating", "Dance", "Upcycling Clothes","Watching Movies"],
        whyLPN: "When I first stepped foot on  the UCI campus, my initial goal was to focus solely on my professional development. However, with LPN, I not only found a group of people that would motivate me to grow professionally, but would also push me to step outside my comfort zone. Looking back, it amazes me how much I have grown since I came to UCI. I learned more in the span of 8 weeks than I have in my entire life, and I know my growth will only continue with the support of my fellow brothers.",
        img: require('../../../../assets/actives/brothers/Sydney_Yu.jpg')
    },
    Nicole_Nguyen: {
        linkedIn: "https://www.linkedin.com/in/nicolexn/",
        homeTown: "Saratoga, CA",
        year: "3rd",
        class: "Rho",
        major: "Business Administration",
        minor: "Information & Computer Science",
        emphasis: "Marketing & Finance",
        practice: "Product Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Data Solutions Marketing Intern":"Moody's Analytics","Marketing Strategy Intern":"ASUCI Media & Technology","Intern":"Automobuild"},
        campusInvolvements: {"Co-VP of Fellowship":"Product Association","Chief Information Officer":"Marketing Strategy Intern","ASUCI Media & Technology":"Lambda Phi Nu","Representative":"Merage Undergraduate Student Association"},
        interests: ["Snowboarding", "Carpool Karaoke", "Reading", "Working Out", "Video Games", "Video Editing"],
        whyLPN: "LPN has truly defined my college experience. I have found a family in this amazing group of like-minded and talented individuals. Not only has LPN helped me to grow professionally, but it has also helped me to grow so much personally as well. The relationships that I have formed and the amazing memories I continue to create are what allow me to confidently say that joining LPN was the best decision I made coming into my second year of college. I couldn't have asked for a better community to be a part of.",
        img: require('../../../../assets/actives/brothers/Nicole_Nguyen.jpg')
    },
    Yllana_Casim: {
        linkedIn: "https://www.linkedin.com/in/yllanacasim/",
        homeTown: "San Diego, CA",
        year: "4th",
        class: "Rho",
        major: "Sociology",
        minor: "Economics",
        emphasis: "Marketing",
        practice: "Marketing Strategy, Product Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Ecosystem Portfolio Scale and Enablement Intern":"Intel", " Alumni and Donors Student Liaison":"UCI TOP Department","Global Marketing Strategy Intern for IoT":"Ingram Micro","Campus Ambassador":"Course Hero","Sales and Marketing Specialist":"Nordstrom"},
        campusInvolvements: {"Co-President":"Management Information Student Society", "Co-VP of Community Development":"Management Information Student Society","Campus Outreach Leader":"TEDxUCIrvine","Consulting Apprentice":"Deloitte Diversity Mentorship Program","Second Tier Family Head":"Kababayan","General Member":"Pi Beta Phi"},
        interests: ["Hiking","Thrifting","Boardgames","Skateboarding","Bullying Nicole"],
        whyLPN: "Found a community of people that inspire me everyday to challenge myself and explore different things, whether it be my career or other activities. I’m constantly growing and learning with the most supportive and growth-oriented people. ",
        img: require('../../../../assets/actives/brothers/Yllana_Casim.jpg')
    },
    Ashley_London: {
        linkedIn: "https://www.linkedin.com/in/ashley-london/",
        homeTown: "Burbank, CA",
        year: "4th",
        class: "Rho",
        major: "Business Administration",
        minor: "",
        emphasis: "Organization & Management, Marketing",
        practice: "Entertainment Payroll, Market Research",
        pronouns: "She/Her/Hers",
        experience: {"Academic Advisor Intern":"U/U Advising Program", "Accounting Assistant":"Revolution Entertainment Services","Non-profit Marketing Consultant":"Team Impact","Social Media Auditor":"Team Impact", "Office Assistant":"Thorburn Chiropractic & Wellness Center"},
        campusInvolvements: {"President":"Marketing Association","Executive Vice President":"Business Careers in Entertainment Club", "Discussion Leader Coordinator":"University Studies 1","Mentor":"Undergraduate/Undeclared Mentorship Program","Hall Representative":"Mesa Court City Council"},
        interests: ["All things Disney", "Thrifting", "Making Pinterest Boards", "Testing Out DIYs"],
        whyLPN: "I chose LPN because of its message to “Grow Fowward. Give Back.” As someone who originally entered UCI as Undeclared, I faced many hardships on my path to switch majors into Business Administration. I wanted to ensure that I could help those that came after me within the undeclared community, and now it is my time to do so in the business community. Alongside this, I wanted to hit the ground running and push myself outside of my comfort zone. LPN has pushed me to become a version of myself I did not know was possible. I am so grateful for LPN because it has helped me continue to strive for bigger and better things, take initiative, and develop relationships that I treasure. The community here is extremely supportive and has helped me grow in so many aspects. LPN is a family that will support you and push you to further your development both professionally and personally.",
        img: require('../../../../assets/actives/brothers/Ashley_London.jpg')
    },
    Eddie_Rios: {
        linkedIn: "https://www.linkedin.com/in/eddierioss/",
        homeTown: "Los Angeles, CA",
        year: "2nd",
        class: "Rho",
        major: "Business Administration",
        minor: "Digital Information Systems",
        emphasis: "Organization & Management",
        practice: "Consulting",
        pronouns: "He/Him/His",
        experience: {"Student Assistant":"Paul Merage Specialty Masters Programs", "Research and Business Analyst":"Mentor Global Consultants"},
        campusInvolvements: {"Recruiter":"Lambda Phi Nu", "Intern":"Undergraduate Business Association","VP of Operations":"Human Resources Management Association","Representative":"Merage Undergraduate Student Association"},
        interests: ["Skiing","Volleyball","Thrifting","Roller skating"],
        whyLPN: "To me, LPN means community. There’s an endless amount of people to be inspired by and always someone to back you up. LPN has opened my eyes to the opportunities that I otherwise would’ve missed out on. Through LPN, I was able to find the person I want to be, and I now have the resources to strive towards becoming that person.",
        img: require('../../../../assets/actives/brothers/Eddie_Rios.jpg')
    },
    Kayla_Wong: {
        linkedIn: "https://www.linkedin.com/in/hfkaylawong/",
        homeTown: "San Lorenzo, CA",
        year: "2nd",
        class: "Rho",
        major: "Business Administration",
        minor: "",
        emphasis: "Marketing",
        practice: "Brand Management ",
        pronouns: "She/Her/Hers",
        experience: {"Business Anaylst Intern (Salesforce Project)":"Accenture", "Marketing Intern":"Volition Beauty",},
        campusInvolvements: {"VP of Professional Development":"Undergraduate Business Association", "Representative":"Merage Undergraduate Student Association","Culture & Relationships director":"Lambda Phi Nu","Operations Associate":"Lambda Phi Nu"},
        interests: ["Gym", "Dance", "Collecting toy cars"],
        whyLPN: "To me, LPN is a safe space for me to grow and authentically be myself. Coming in as a first-year, I felt very lost when it came to starting my professional career. I was super overwhelmed which is why I initially rushed for LPN. After the first quarter, I have realized that what LPN has provided me is much more than just professional guidance. From LPN I have gained a new support system and family whom I love unconditionally. ",
        img: require('../../../../assets/actives/brothers/Kayla_Wong.jpg')
    },

    // Sigma
    Deena_Toofan: {
        linkedIn: "https://www.linkedIn.com/in/deenatoofan",
        homeTown: "Milpitas, CA",
        year: "4th",
        class: "Sigma",
        major: "Business Administration",
        minor: "",
        emphasis: "Accounting",
        practice: "Audit",
        pronouns: "She/Her/Hers",
        experience: {"Finance Intern":"Sodexo","Accounting Intern":"Solexir Technology"},
        campusInvolvements: {"Culture & Relationships Director":"Lambda Phi Nu"},
        interests: ["Photography","Volleyball","Hiking","Video games","Camping","Karaoke"],
        whyLPN: "Transferring into UCI, I couldn't find a community where I felt like I belonged. It is safe to say, LPN has given me everything I have wanted and more for my college experience. I have developed life-long friendships with my fellow brothers, and I am constantly surrounded by driven individuals that motivate me every day. Everyone here is a role model, and I am so lucky and grateful to be a part of this fraternity.",
        img: require('../../../../assets/actives/brothers/Deena_Toofan.jpg'),
    },
    Hans_Chang: {
        linkedIn: "https://www.linkedin.com/in/hans-chang/",
        homeTown: "Taipei, Taiwan",
        year: "3rd",
        class: "Sigma",
        major: "Business Economics",
        minor: "Information and Computer Sciences",
        emphasis: "",
        practice: "Fintech, Marketing Analytics ",
        pronouns: "He/Him/His",
        experience: {"E-commerce Marketing Analysis Intern":"BenQ Corporation", "Accounting Assistant":"MediaTek Inc."},
        campusInvolvements: {"Chief Finance Officer":"Taiwanese National Organization", "Media Team (Department of Marketing)":"Taiwanese National Organization", "Mentee":"Undergraduate Business Association",},
        interests: ["Basketball","Formula 1","Thrifting","Skiing","Hanging out with friends"],
        whyLPN: "After having freshman year entirely online, I realized I didn't have much time left. I was not only trying to push myself out of my comfort zone but also looking for a community that could help me develop both personally and professionally. I am thankful for what LPN has taught me and shaped me into the person I am today.",
        img: require('../../../../assets/actives/brothers/Hans_Chang.jpg'),
    },
    Jaejin_Kim: {
        linkedIn: "https://https://www.linkedin.com/in/jaejink/",
        homeTown: "Busan, South Korea",
        year: "2nd",
        class: "Sigma",
        major: "Computer Science",
        minor: "",
        emphasis: "",
        practice: "Software Engineering, Web Development",
        pronouns: "He/Him/His",
        experience: {"Website Student Assistant":"UCI School of Medicine"},
        campusInvolvements: {"Corporate Organizer":"Hack at UCI","Webmaster":"Lambda Phi Nu","Executive Associate":"Lambda Phi Nu"},
        interests: ["Cooking","Sports","Gym","Late night walks","Nap"],
        whyLPN: "I chose LPN because I wanted to find a community where I feel like I belong in. I never felt like I had to be someone else other than myself here; I am grateful that I can truly be myself in this community. People here inspire and motivate me push myself to be a better version of myself everyday. ΛΦΝ is a community that you can't find anywhere else. I'm thankful to have every one of them in my life, and I am happy that I can call them my brothers.",
        img: require('../../../../assets/actives/brothers/Jaejin_Kim.jpg'),
    },
    Jodie_Tai: {
        linkedIn: "https://www.linkedin.com/in/jodieetai/",
        homeTown: "San Lorenzo, CA",
        year: "4th",
        class: "Sigma",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Real Estate, Finance",
        pronouns: "She/Her/Hers",
        experience: {"Real Estate Controls Intern":"The Walt Disney Company"},
        campusInvolvements: {"Chief Financial Officer":"Lambda Phi Nu","Finance Associate":"Lambda Phi Nu", "Mentor":"Undergraduate Business Association", "Undergraduate Researcher":"UCI School of Education"},
        interests: ["Coffee", "Yoga", "Traveling", "Fashion", "Food", "Art", "Interior design", "Organizing things"],
        whyLPN: "As a transfer student, I feared not being able to find a community at UCI. Little did I know that deciding to rush Lambda Phi Nu after stumbling across the Winter 2022 Recruitment post on Facebook would be a pivotal point in my college journey. Being surrounded by individuals with an infinite amount of perseverance has motivated me to step out of my comfort zone and maximize my potential. But most importantly, LPN has become a forever family.",
        img: require('../../../../assets/actives/brothers/Jodie_Tai.jpg'),
    },
    Julie_Hsieh: {
        linkedIn: "https://www.linkedin.com/in/haonihsieh/",
        homeTown: "Taipei, Taiwan",
        year: "2nd",
        class: "Sigma",
        major: "Business Economics",
        minor: "",
        emphasis: "Marketing",
        practice: "Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Marketing  Intern":"LnData", "Marketing Intern":"Day and Night International CO., LTD"},
        campusInvolvements: {"Marketing Mentee":"Undergraduate Business Association", "Marketing Director":"Lambda Phi Nu", "Information Associater":"Lambda Phi Nu"},
        interests: ["Hanging out with friends", "Sleeping","Going to the beach","Skin Care","Make up","Online Shopping", "Outdoor Activities"],
        whyLPN: "I choose LPN because I want a family like community. A community that can inspire me and support me whenever I need help. LPN not only teach me what professionalism is but also let me step out of my comfort zone. I'm glad that I'm a part of this community, and I'm thankful for all the things that LPN gives me.",
        img: require('../../../../assets/actives/brothers/Julie_Hsieh.jpg'),
    },
    Justin_Chao: {
        linkedIn: "https://www.linkedin.com/in/justin-chao/",
        homeTown: "Anaheim, CA",
        year: "2nd",
        class: "Sigma",
        major: "Business Administration",
        minor: "Psychological Science ",
        emphasis: "Organizational Management",
        practice: "Human Resources, Product Management",
        pronouns: "He/Him/His",
        experience: {"HR Intern":"Western Digital", "Digital Marketing Manager":"Luxart Lights","Product Marketing Intern":"Terra Pocket","Social Media Manager":"Terra Pocket"},
        campusInvolvements: {"VP of External Relations":"Human Resources Management Association","Representative":"Merage Undergraduate Student Association","Associate Consultant":"Students Consulting for Nonprofit Organizations","Recruiter":"Lambda Phi Nu","Alumni Relations Director":"Lambda Phi Nu"},
        interests: ["Basketball", "Spikeball","Golfing","Photography","Lifting","Golfing","Pool"],
        whyLPN: "LPN is a group of people that I can call my family. They are always there for me for both professional and personal help!",
        img: require('../../../../assets/actives/brothers/Justin_Chao.jpg'),
    },
    Ruby_Ko: {
        linkedIn: "https://www.linkedin.com/in/korubyko/",
        homeTown: "Taichung, Taiwan",
        year: "2nd",
        class: "Sigma",
        major: "Business Administration",
        minor: "Digital Information System",
        emphasis: "Marketing, Management",
        practice: "Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Creative Director Assistant Intern":"Koplus International","Marketing Intern":" Lazy Cloud","Sales Assistant Intern":"Smith & Associates","Student Assistant":"Paul Merage School of Business Career Center","Sports Coordinator":"Morrison Academy"},
        campusInvolvements: {"Intern":"UBA","Finance Director":"MA","Marketing Director":"Lambda Phi Nu",},
        interests: ["Volleyball", "Soccer", "Basketball", "Thrifting", "Farmers Market", "Concerts"],
        whyLPN: "LPN brought me a community that I am able to lean on both professionally and personally. I've met people that shaped me to become more than I could ever imagine myself to be.",
        img: require('../../../../assets/actives/brothers/Ruby_Ko.jpg'),
    },
    Qui_Hoang: {
        linkedIn: "https://www.linkedin.com/in/quihoang/",
        homeTown: "Oakland, CA",
        year: "3rd",
        class: "Sigma",
        major: "Business Administration",
        minor: "",
        emphasis: "Accounting, Finance",
        practice: "Accounting",
        pronouns: "She/Her/Hers",
        experience: {"Career Center Student Assistant":"Paul Merage School of Business","Brand Ambassador":"GIST", "Studnet Ambassador":"Surgent CPA Review","Rotational Intern":"Grant Thorton"},
        campusInvolvements: {"Committee Board Officer":"Accounting Association","Alumni Engagement Intern":"Adminstrative Intern Program","Mentee":"Antleader Mentorship Program","ACE Intern":"Vietnamese Student Association","Member":"Chinese Association","Member":"Real Estate Association"},
        interests: ["Hiking","Baking","Travel","Trying new food spots","Late-night drives","Anime","Disney","Boardgames","Karaoke"],
        whyLPN: "LPN has given me a tight-knit community of individuals who constantly inspire and encourage me to step out of my comfort zone, both professionally and personally. I've already learned so much about myself and grown professionally in the short time that I've been here, and it's all thanks to all the supportive people I've met in LPN.",
        img: require('../../../../assets/actives/brothers/Qui_Hoang.jpg'),
    },
    Will_Bordessa: {
        linkedIn: "https://www.linkedin.com/in/will-bordessa/",
        homeTown: "Napa, CA",
        year: "4th",
        class: "Sigma",
        major: "Business Administration",
        minor: "Urban and Regional Planning",
        emphasis: "Organization and Management",
        practice: "Consulting",
        pronouns: "He/Him/His",
        experience: {"Business Advisory Services Intern":"Slalom","E-commerce Team Member":"Whole Foods Market","Social Media Marketing Manager":"Calvary Chapel Bible College Japan"},
        campusInvolvements: {"VP of Operations":"Human Resources Management Association","Ministry Team":"Reformed University Fellowship"},
        interests: ["Volleyball","Gaming","Longboarding"],
        whyLPN: "I knew LPN was the right place for me during rush when I realized I was learning so much from the brothers I talked to. Even before I received a bid, they gave me confidence in myself and in my ability to chase a successful career. They've not only given me professional development but a community of life-long friends and dependable individuals who are truly invested in me, and that is what motivates me to give back.",
        img: require('../../../../assets/actives/brothers/Will_Bordessa.jpg'),
    },
    // Tau
    Alex_Zhou: {
        linkedIn: "https://www.linkedin.com/in/zhouaz/",
        homeTown: "Southlake, TX",
        year: "1st",
        class: "Tau",
        major: "Computer Science",
        minor: "",
        emphasis: "",
        practice: "Software Engineering",
        pronouns: "He/Him/His",
        // experience: {"Business Advisory Services Intern":"Slalom","E-commerce Team Member":"Whole Foods Market","Social Media Marketing Manager":"Calvary Chapel Bible College Japan"},
        campusInvolvements: {"Mentee":"Management Information Student Society","Member":"Chinese Association"},
        interests: ["Video Games", "Reading", "Traveling", "Online Shopping", "Hanging out with friends"],
        whyLPN: "LPN gave me a supportive community that will undoubtedly have my back for life. I rushed with the intention of gaining professional help, but I ended up leaving with so much more.",
        img: require('../../../../assets/actives/brothers/Alex_Zhou.jpg')
    },
    Brandyn_Huynh: {
        linkedIn: "https://www.linkedin.com/in/brandyn-le-huynh/",
        homeTown: "Milpitas, CA",
        year: "3rd",
        class: "Tau",
        major: "Business Administration",
        minor: "",
        emphasis: "Marketing and Organizational Management",
        practice: "Human Resources",
        pronouns: "He/Him/His",
        experience: {"Shift Lead":"Tea Doraku", "Founder": "B's Premium Teas", "English Second Language Tutor": "San Jose City College"},
        campusInvolvements: {"Co-Company Relations Director":"Marketing Association"},
        interests: ["Evening runs", "Biking", "Concerts", "Painting", "Thrifting", "Trying different food places", "Learning different instruments" ],
        whyLPN: "Coming in as a transfer, I wanted to get involved as much as possible and seek out any opportunities for personal growth and professional development. I still had a lot of learning about the different industries within the business realm and was still determining what I wanted to pursue career-wise. However, once joining LPN, I had the chance to be surrounded by a community of unique and motivated individuals who supported me by helping me figure out my career goals and also allowing me to learn from their experiences personally and professionally. LPN is a tight-knit community that fosters strong brotherhood and has given me a community of people I know I can always depend on and draw inspiration from.",
        img: require('../../../../assets/actives/brothers/Brandyn_Huynh.jpg')
    },
    Denise_Wei: {
        linkedIn: "https://www.linkedin.com/in/denise-wei/",
        homeTown: "San Francisco, CA",
        year: "3rd",
        class: "Tau",
        major: "Business Administration, Data Science",
        minor: "",
        emphasis: "Accounting",
        practice: "Audit",
        pronouns: "She/Her/Hers",
        experience: {"Incoming Audit Intern":"PwC", "Junior Golf Coach": "First Tee of San Francisco"},
        campusInvolvements: {"Committee Board Officer":"Accounting Association", "Finance Associate":"Lambda Phi Nu"},
        interests: ["Golf", "Snowboarding", "Card games", "Trying new extreme sports" ],
        whyLPN: "I wanted to immerse myself in a community of driven and supportive individuals. Everyone at LPN carries themselves with confidence and are always willing to help out, even those outside of the fraternity. Seeing this through rush was what ultimately led me to join LPN. Through LPN, I have been able to form meaningful relationships with both my Pledge Class and Active Brothers, and I can always rely on them for personal and professional help. These connections are unique in that I know they will extend beyond college.",
        img: require('../../../../assets/actives/brothers/Denise_Wei.jpg')
    },
    Evan_Choe: {
        linkedIn: "https://www.linkedin.com/in/evan-c-choe/",
        homeTown: "Irvine, CA",
        year: "1st",
        class: "Tau",
        major: "Business Administration",
        minor: "",
        emphasis: "Finance, Marketing",
        practice: "Consulting, Product Management",
        pronouns: "He/Him/His",
        experience: {"Co-Founder":"Echo Speech & Debate"},
        campusInvolvements: {"Executive Associate":"Lambda Phi Nu", "Alumni Relations Intern":"Lambda Phi Nu"},
        interests: ["Hanging Out", "Writing", "Reading", "History & Philosophy", "Going on Walks", "Skiing", "Soccer", "Video Games", "Wikipedia Rabbit Holes", "Guessing Peoples' MBTI" ],
        whyLPN: "I have never grown faster within such a short period of time as I have here in LPN. As long as I put in the effort, I knew I was improving every step of the way. More importantly, there were rarely times I experienced something alone. In common struggle and common joy, I could not imagine myself in LPN without those who were there to support me. Now, I have a community with which to further cultivate such meaningful relationships and give back with sincerity.",
        img: require('../../../../assets/actives/brothers/Evan_Choe.jpg')
    },
    Grace_Xu: {
        linkedIn: "https://www.linkedin.com/in/grace-xuuu/",
        homeTown: "Birmingham, AL",
        year: "2nd",
        class: "Tau",
        major: "Business Economics",
        minor: "",
        emphasis: "",
        practice: "Marketing",
        pronouns: "She/Her/Hers",
        experience: {"Desk Assistant":"Langson Library","Music Radio Host":"KUCI", "Music Librarian":"KUCI"},
        campusInvolvements: {"Audio Intern":"KUCI"},
        interests: ["Doodling", "Shopping for clothes", "Gaming", "Listening to music", "Creating Spotify playlists", "Playing violin" ],
        whyLPN: "I chose LPN because of the tight-knit community and the message. Everyone here genuinely wants to see you grow professionally and is willing to help you along the way. LPN is like my second family!",
        img: require('../../../../assets/actives/brothers/Grace_Xu.jpg')
    },
    Jacob_Uradnik: {
        linkedIn: "https://www.linkedin.com/in/jacob-uradnik/",
        homeTown: "Sammamish, WA",
        year: "2nd",
        class: "Tau",
        major: "Business Administration",
        minor: "",
        emphasis: "Organization and Management",
        practice: "",
        pronouns: "He/Him/His",
        experience: {"Catering Chef":"Foodz","Aldarra":"Outdoor Services"},
        campusInvolvements: {"Representative":"Merage Undergraduate Student Association"},
        interests: ["Cooking", "Bouldering", "Skiing", "Hiking", "Fishing", "Thrifting", "Listening to music", "Spending quality time with friends" ],
        whyLPN: "I struggled a lot during my first year at UCI. Coming from out of state, I was in a completely new environment. I had a hard time making friends and couldn’t find the motivation to complete any of my school work. I didn’t like being a business administration major, and I wanted to transfer. The following year, I was dreading going back to UCI. I knew I needed to get involved around campus more, but I didn’t know how. When I first rushed for LPN, it gave me a new sense of direction. Not only did I meet people who I now know will be my lifelong friends, but I finally felt motivated to pursue business. The brotherhood and direction that LPN gave me has completely changed my college experience, and I am forever grateful.",
        img: require('../../../../assets/actives/brothers/Jacob_Uradnik.jpg')
    },
    Madhu_Sharma: {
        linkedIn: "https://www.linkedin.com/in/madhuxsharma/",
        homeTown: "Plano, TX",
        year: "2nd",
        class: "Tau",
        major: "Computer Science",
        minor: "",
        emphasis: "",
        practice: "Software Engineering, Entrepreneurship",
        pronouns: "He/Him/His",
        experience: {"Co-Founder":"Bonsai","Software Development Engineer Intern":"Amazon","Software Developer":"Delta System & Software, Inc."},
        campusInvolvements: {"Technical Lead":"Commit the Change","Information Associate":"Lambda Phi Nu"},
        interests: ["Hanging out with friends", "Trying out new foods", "Videogames", "Music", "Anime", "K-Pop Dance", "Volleyball, Weightlifting" ],
        whyLPN: "I initially wanted to join a business fraternity because I value creating life-long relationships with others. Not the type of friends you only hang out with, but also the ones that will push you to be the best version of yourself. Upon hearing about Lambda Phi Nu, I connected with the motto: 'Grow Forward. Give Back.' Throughout my life, I have had amazing people help me grow forward, and I enjoy helping people, especially those who used to be in my position. Since joining LPN, I have enjoyed every interaction I have with the Active Brothers, and I look forward to spending more time with them in the upcoming years.",
        img: require('../../../../assets/actives/brothers/Madhu_Sharma.jpg')
    },
    Rainer_Setiawan: {
        linkedIn: "https://www.linkedin.com/in/rainer-setiawan/",
        homeTown: "Chino Hills, CA",
        year: "3rd",
        class: "Tau",
        major: "Business Administration",
        minor: "",
        emphasis: "Finance and Information Systems",
        practice: "Product Design",
        pronouns: "He/Him/His",
        experience: {"Supervisor":"Tastea","Assistant Tennis Coach":"Woodbridge High School"},
        campusInvolvements: {"TCohort":"LEADS Program","Information Associate":"Design at UCI "},
        interests: ["Tennis", "Basketball", "Video Games", "Anime", "Manga", "Sleep" ],
        whyLPN: "Despite being from the area, I came to UCI knowing very few people. As a transfer and not knowing what career path to choose, rushing LPN was the best decision I could have made. I learned the directions I want to take stepping into the professional world and how to better socialize with others. My growth through joining LPN has been significant, and I look forward to using what I have learned to succeed. As an LPN brother, I know that I am not alone. It is always reassuring to know there are others I can rely on and will always be there for me every step of the way.",
        img: require('../../../../assets/actives/brothers/Rainer_Setiawan.jpg')
    },
    Tannvi_Banerjee: {
        linkedIn: "https://www.linkedin.com/in/tannvi-banerjee/",
        homeTown: "Fremont, CA",
        year: "1st",
        class: "Tau",
        major: "Computer Science",
        minor: "",
        emphasis: "",
        practice: "Software Engineering, Venture Capital",
        pronouns: "She/Her/Hers",
        experience: {"Computational Economics Researcher":"New York University","Data Science Intern":"Stanford Daily", "Computational Biology Researcher":"ASDRP Research Labs"},
        campusInvolvements: {"Software Engineering Fellow":"Product Association","Professional Development Intern":"Management Information Student Society","Software Developer":"Commit the Change"},
        interests: ["Baking", "Kayaking", "Fashion", "Curating Spotify Playlists", "Collecting Succulents", "Making Pinterest Boards", "Badminton", "Crossword Puzzles", "Watching Crime/Horror Movies", "Eating", "Napping", "Petting Dogs" ],
        whyLPN: "I rushed LPN looking to find a tight-knit community as a first-year in college. Since joining LPN, I have met some of the most genuine people who have pushed me to grow and challenge my own perspective. What I value the most about this community is how supportive everyone is. I can rely on the Active Brothers to help me navigate the ups and downs of college life. And because everyone is always up to something cool, I end up having the most interesting conversations with other brothers!",
        img: require('../../../../assets/actives/brothers/Tannvi_Banerjee.jpg')
    },
    Teresa_Chu: {
        linkedIn: "https://www.linkedin.com/in/teresa-chu56/",
        homeTown: "Taipei, Taiwan",
        year: "2nd",
        class: "Tau",
        major: "Business Administration",
        minor: "Informatics",
        emphasis: "Finance, Information Systems",
        practice: "Corporate Finance, ",
        pronouns: "She/Her/Hers",
        experience: {"Student Assistant":"UCI Paul Merage AEC","Global Investment Strategy & Technology Equity Research Intern":"Taishin Securities Investment Advisory"},
        campusInvolvements: {"Operations Associate":"Lambda Phi Nu","Administrative Student Intern":"Administrative Internship Program","Director of External Relations":"FLA","LIFEvest Resident Advisor":"UCI Paul Merage CIWM","LIFEvest Alumni Mentorship Program (LAMP) Mentor":"UCI Paul Merage CIWM","Goldman Sachs Excel Skills for Business Virtual Experience Program":"UC Investment Academy, Pilot Program with Forage","Mentor":"IPG","Scholar Committee Member":"IPG","Mentee":"IPG","Intern":"UBA","Mentee":"UBA","Mentee":"MAISS"},
        interests: ["Major Foodie", "Cooking", "Traveling", "Skiing", "Hiking", "Swimming", "Gymming", "Skincare", "Hanging out with friends" ],
        whyLPN: "LPN is a place where I can 'Grow Forward. Give Back' to the community with a group of driven people. I am grateful that I have learned and been helped a lot during my time as a mentee in my freshmen year. Therefore, I am eager to advocate the virtuous cycle of mentorship, as I am constantly learning from others and offering help to others. I love how this family empowers people to become the best version of themselves.",
        img: require('../../../../assets/actives/brothers/Teresa_Chu.jpg')
    },
};

export default { profiles };